-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 17, 2024 at 10:09 AM
-- Server version: 10.6.19-MariaDB-cll-lve
-- PHP Version: 8.1.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `qurascxb_quraanclassesus`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl`
--

CREATE TABLE `tbl` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `phone` varchar(50) NOT NULL,
  `country` varchar(50) NOT NULL,
  `msg` varchar(300) NOT NULL,
  `date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `tbl`
--

INSERT INTO `tbl` (`id`, `name`, `email`, `phone`, `country`, `msg`, `date`) VALUES
(1, 'Moiz Ahmed ', 'moizsheikh646@gmail.com', '', '', '', '2023-02-10 12:52:06'),
(2, 'Moiz Ahmed ', 'moizsheikh646@gmail.com', '03213239633', 'pakistan', 'some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text ', '2023-02-10 14:58:43'),
(3, 'Moiz Ahmed ', 'moizsheikh646@gmail.com', '03213239633', 'pakistan', 'some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text some text ', '2023-02-10 14:59:41'),
(4, 'Danish', 'danish@yahoo.com', '03265998989', 'Pakistan', 'some text', '2023-02-10 15:03:17'),
(5, 'Moiz Ahmed ', 'moiz@yahoo.com', '03213239633', 'USA', 'some text', '2023-02-14 02:50:23'),
(6, 'Danish', 'engineer_farhan@yahoo.com', '03265998989', 'pakistan', 'some text', '2023-02-14 02:56:03'),
(7, 'Moiz Ahmed ', 'moizsheikh646@gmail.com', '03213239633', 'pakistan', 'i am moiz', '2023-02-14 03:00:12'),
(8, 'huney', 'huneykhan17@gmail.com', '032321699', 'USA', 'some text', '2023-02-14 04:31:58'),
(9, 'Danish', 'huneykhan17@gmail.com', '03213239633', 'UK', 'I am huney khan', '2023-02-14 04:33:42'),
(10, 'huney khan', '03213239633', 'huneykhan17@gmail.com', 'Canada', 'i am huney khan dear', '2023-02-14 06:13:26'),
(11, 'Moiz Ahmed ', '03265998989', 'huneykhan17@gmail.com', 'pakistan', 'i am raheem', '2023-02-14 06:15:12'),
(12, 'Kashan', '025852369', 'huneykhan17@gmail.com', 'Landhi', 'checked', '2023-02-14 06:16:14'),
(13, 'Hassaan', '087989878', 'hassan@gmail.com', 'Pakistan ', 'Salam I would like to enroll my kids ', '2023-02-17 05:21:05'),
(14, 'Hassaan', '087989878', 'khassaan54@gmail.com', 'Pakistan ', 'Salam I would like to enroll my kids ', '2023-02-17 05:23:16'),
(15, 'Hassaan', '03032868853', 'Khassaan54@gmail.com', 'Pakistan', 'salam ', '2023-02-17 13:39:24'),
(16, 'Hassaan Raza', 'ashsas', 'Khassaan54@gmail.com', 'Pakistan', 'adasa', '2023-02-17 13:41:05'),
(17, '', '', '', '', '', '2023-02-17 13:41:14'),
(18, 'Bashar', '7373737737', 'bashar@gmail.com', 'Pakistan ', 'Salam', '2023-02-18 01:53:42'),
(19, 'Check ', '33342', 'check@gmail.com', 'Pakistan ', 'Salam', '2023-02-18 02:16:26'),
(20, 'Check ', 'Isuajahsh', 'check2@gmail.com', 'Pakistan ', 'Slalan', '2023-02-18 02:19:35'),
(21, 'Check3 ', 'Jajsjsj', 'check@gmail.com', 'Pakistan ', 'Slama', '2023-02-18 02:26:48'),
(22, 'Moiz', 'alphabet', 'moiz@yahoo.com', 'pakistan', 'Checked', '2023-02-20 02:20:19'),
(23, 'Moiz Ahmed ', 'abcd', 'moiz@yahoo.com', 'pakistan', 'checked', '2023-02-20 02:21:06'),
(24, 'Moiz Ahmed ', '03213239633', 'moizsheikh646@gmail.com', 'pakistan', 'dasdadas', '2023-02-20 02:22:47'),
(25, 'Moiz Ahmed ', '03213239633', 'moizsheikh646@gmail.com', 'pakistan', 'some text', '2023-02-20 02:23:36'),
(26, 'Moiz Ahmed ', '03213239633', 'moizsheikh646@gmail.com', 'pakistan', 'checked', '2023-02-20 02:25:33'),
(27, 'Moiz Ahmed ', '03213239633', 'moizsheikh646@gmail.com', 'pakistan', 'cheked', '2023-02-20 02:47:42'),
(28, 'Hassaan Raza', '03032868853', 'Khassaan54@gmail.com', 'Pakistan', 'salam', '2023-02-20 02:56:52'),
(29, 'Moiz ', 'asdf', 'moiz@yahoo.com', 'pakistan', 'checked', '2023-02-22 04:27:48'),
(30, 'afdf', '3252563152', '123@gmail.com', 'sdfas', 'sdfad', '2023-02-22 04:30:02'),
(31, 'afdf', '3252563152', '123@gmail.com', 'sdfas', 'sdfad', '2023-02-22 04:31:18'),
(32, 'fadf', '3232564856', 'moiz@gmail.com', 'fasd', 'asdf', '2023-02-22 05:17:23'),
(33, 'afdf', '03232564899', 'moiz@gmail.com', 'pakistan', 'dfadfasfsfasf', '2023-02-22 05:29:31'),
(34, 'Hassaan ', '03032868853', 'check@gmail.com', 'Pakistan', 'checking ', '2023-02-22 05:30:22'),
(35, 'Raheem ', '03182604672', 'demo@gmail.com', 'sdfas', 'fafasdfsdf', '2023-02-22 06:23:26'),
(36, 'Hassaan Raza', '03032868853', 'Khassaan54@gmail.com', 'Pakistan', 'salam ', '2023-02-22 06:32:51'),
(37, 'alabama', '03032868853', 'alabama4@gmail.com', 'Pakistan', 'alabama', '2023-02-22 06:41:21'),
(38, 'Home page Final check ', '13322446958', 'final@gmail.com', 'pakistan', 'final checking home page contact form ', '2023-02-22 17:57:33'),
(39, 'contac.pht final check', '13322446958', 'confinalcheck@gmail.com', 'USA', 'contact.php final check ', '2023-02-22 17:59:16'),
(40, 'Raheem ', '03182604672', 'demo@gmail.com', 'sdfas', '', '2023-02-23 04:04:05'),
(41, 'alabama check', '03032868853', 'alabama@gmail.com', 'Pakistan', 'Alabama checking', '2023-02-23 05:13:49'),
(42, 'Hassaan Raza', '3032868853', 'Khassaan54@gmail.com', 'Pakistan', 'salam ', '2023-02-23 17:37:13'),
(43, 'Moiz Ahmed', '1234556987', 'moizsheikh646@gmail.com', 'pakistan', 'Checked', '2023-02-24 09:35:21'),
(44, 'kashan khan', '1236547891', 'kashan@yahoo.com', 'USA', 'Checked', '2023-02-24 09:36:59'),
(45, 'Raheem Siddiqui', '0318260467', 'jxg72717@cdfaq.com', 'adsfadsf', 'adsfasdf', '2023-02-24 13:22:51'),
(46, 'usman', '3032868853', 'usman@gmail.com', 'pakistan', 'salam', '2023-02-24 18:13:23'),
(47, 'usman', '3032868853', 'usman@gmail.com', 'pakistan', 'salam', '2023-02-24 18:16:26'),
(48, 'new Mexico ', '3032868853', 'newmex@gmail.com', 'Pakistan', 'New Mexico checking page ', '2023-03-03 12:48:50'),
(49, 'RaymondSmets', '5446511355', 'no.reply.SemWilson@gmail.com', 'United Arab Emirates', 'Hi! quraanclasses.us \r\n \r\nDid you know that it is possible to send letter correctly and legitimately? We propose a legal method of sending business proposals through feedback forms. These kinds of feedback forms can be seen on many webpages. \r\nWhen such messages are sent, no personal data is used, a', '2023-03-30 22:29:07'),
(50, 'lili', '8378254346', 'atts@email.com', 'United States', 'Hello', '2023-04-04 03:49:02'),
(51, 'alabama', '1234567892', 'moiz@gmail.com', 'pakistabn', 'ghj', '2023-04-15 00:11:23'),
(52, 'Raheem Siddiqui', '0318260467', 'moizsheikh646@gmail.com', 'sdsd', 'fadsfa', '2023-04-15 13:56:53'),
(53, 'Home ', '8786876765', 'home@gmail.com', 'Pakistan ', 'Salam ', '2023-04-18 05:24:00'),
(54, 'Mike Philips\r\n', '7854144802', 'no-replyexcita@gmail.com', 'Netherlands Antilles', 'Howdy \r\n \r\nThis is Mike Philips\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an immedia', '2023-04-20 07:36:54'),
(55, 'Tigran Ayrapetyan', '4534227301', 'ujn2esbgakah@opayq.com', 'Bahrain', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. \r\nWe have a structured joint venture investment plan in which we are interested in an annual return on investm', '2023-04-25 21:48:28'),
(56, 'Mike Phillips\r\n', '2776431420', 'no-replyexcita@gmail.com', 'New Zealand', 'If you have a local business and want to rank it on google maps in a specific area then this service is for you. \r\n \r\nGoogle Map Stacking is one of the best ways to rank your GMB in a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThanks and Rega', '2023-04-27 15:46:46'),
(57, 'Mike Raleigh\r\n', '3134001330', 'no-replyexcita@gmail.com', 'United States', 'Hi there \r\n \r\nJust checked your quraanclasses.us in MOZ and saw that you could use an authority boost. \r\n \r\nWith our service you will get a guaranteed Domain Authority score within just 3 months time. This will increase the organic visibility and strengthen your website authority, thus getting it st', '2023-04-30 15:39:23'),
(58, 'Mike Turner\r\n', '5387443204', 'no-replyexcita@gmail.com', 'Taiwan', 'Greetings \r\n \r\nI have just analyzed  quraanclasses.us for the ranking keywords and saw that your website could use a boost. \r\n \r\nWe will enhance your ranks organically and safely, using state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info:', '2023-05-02 15:43:20'),
(59, 'Mike Wood\r\n', '3488645052', 'no-replyexcita@gmail.com', 'Netherlands Antilles', 'Greetings \r\n \r\nThis is Mike Wood\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an immedi', '2023-05-16 01:28:15'),
(60, 'ODOZIAKUCHI', '4516046372', 'hello@odoziakuchi.com', 'Italy', 'Good day! \r\n \r\nLooking for Heirloom fine Jewellery? \r\n \r\nODOZIAKUCHI is an exciting jewellery brand that celebrates individuality, our mission is to create sentimental jewellery with meaning that move on to become heirlooms for generations. \r\n \r\nWe pride ourselves in making sustainable timeless jewe', '2023-06-02 20:51:22'),
(61, 'Mike Ferguson\r\n', '5112826537', 'no-replyexcita@gmail.com', 'Taiwan', 'Greetings \r\n \r\nI have just analyzed  quraanclasses.us for the ranking keywords and saw that your website could use a push. \r\n \r\nWe will improve your ranks organically and safely, using state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info: ', '2023-06-03 20:09:16'),
(62, 'Tigran Ayrapetyan', '5652110761', 'ujn2esbgakah@opayq.com', 'Bahrain', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. \r\nWe have a structured joint venture investment plan in which we are interested in an annual return on investm', '2023-06-06 02:28:01'),
(63, 'Susan Karsh', '2687022738', 'susankarsh.myaa@gmail.com', 'New Zealand', 'Hello, \r\n \r\nI was on your site today and I wanted to see if you would be open to getting a FREE 14-Day trial of our AI Agents, like ChatGPT, but much better. Plus, our plans start at just $1 per month if you decide to continue. \r\n \r\nOur AI Agents Can: \r\n \r\nâ€¢	Assist your team with tasks, projects a', '2023-06-07 09:32:35'),
(64, 'Mike Higgins\r\n', '0872443170', 'no-replyexcita@gmail.com', 'United States', 'Good Day \r\n \r\nI have just checked  quraanclasses.us for onsite errors and saw that your website has a handful of issues which should be addressed. \r\n \r\nNo matter what you are offering or selling, having a poor optimized site, full of bugs and errors, will never help your ranks. \r\n \r\nLet us fix your ', '2023-06-10 13:34:50'),
(65, 'Mike Dickinson\r\n', '6634251280', 'no-replyexcita@gmail.com', 'Netherlands Antilles', 'Greetings \r\n \r\nThis is Mike Dickinson\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an i', '2023-06-13 19:35:40'),
(66, 'Josephpneub', '4446353288', 'support1@sparkweb.vip', 'Jordan', 'We are a software outsourcing company from China, if you have any software customization or it technical service needs can contact us, if you need a long-term technical team to develop and maintain different projects for you, we will be your best choice, we will cooperate with your time zone, 7 * 24', '2023-06-14 18:16:41'),
(67, 'Mike Garrison\r\n', '8380750657', 'no-replyexcita@gmail.com', 'United States', 'Hi there \r\n \r\nJust checked your quraanclasses.us in MOZ and saw that you could use an authority boost. \r\n \r\nWith our service you will get a guaranteed Domain Authority score within just 3 months time. This will increase the organic visibility and strengthen your website authority, thus getting it st', '2023-06-20 09:11:24'),
(68, 'Mike Davidson\r\n', '4541727562', 'no-replyexcita@gmail.com', 'New Zealand', 'If you have a local business and want to rank it on google maps in a specific area then this service is for you. \r\n \r\nGoogle Map Stacking is one of the best ways to rank your GMB in a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThanks and Rega', '2023-06-21 00:08:52'),
(69, 'Susan', '2048157742', 'susankarsh.myaa@gmail.com', 'Germany', 'Hello, \r\n \r\nA little over a week ago, I sent a message that I was on your site, and wanted to see if you would be open to getting a FREE 14-Day trial of our AI Agents, like ChatGPT, but with loads of enhancements and hundreds of skillful AI agents that can be hand-picked to cater to your specific re', '2023-06-24 05:42:00'),
(70, 'Waheed Mohammed', '6772731576', 'ujn2esbgakah@opayq.com', 'United Arab Emirates', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. We have a structured joint venture investment plan in which we are interested in an annual return on investmen', '2023-06-26 05:27:37'),
(71, 'Andrewcault', '2668727143', 'iunskiygipertonik@gmail.com', 'United States', 'Ethinyl buy, discount! without prescription. \r\nGranisetron buy, discount! without prescription. \r\nNorethindrone buy, discount! without prescription. \r\nClozapine buy, discount! without prescription. \r\n \r\nRoxithromycin buy, discount! without prescription. \r\nStromectol buy, discount! without prescripti', '2023-07-04 02:12:20'),
(72, 'Mike Roger\r\n', '5818033318', 'mikePubsreab@gmail.com', 'United States', 'Hi there, \r\n \r\nI have recently conducted an analysis of quraanclasses.us for onsite errors and discovered that your website presents several issues that require attention. \r\n \r\nRegardless of the product or service you are offering or selling, possessing a site that is inadequately optimized and rife', '2023-07-05 04:09:48'),
(73, 'RobertSkeve', '6035132541', 'alfredegov@gmail.com', 'France', 'Sveiki, es gribÄ“ju zinÄt savu cenu.', '2023-07-08 14:35:34'),
(74, 'Daniel', '5730301832', 'support@newlightdigital.com.hubspot-inbox.com', 'Ireland', 'Hello, \r\n \r\nWe are offering a discount on all our digital marketing services through the end of the year. If you were ever thinking about doing stuff like this, now is the time. This is an amazing deal. Just pick one or more packages below. \r\n \r\n1. Write, optimize, and format 3 blog posts per month ', '2023-07-12 12:38:48'),
(75, 'Mike Webster\r\n', '6407125012', 'mikeexcita@gmail.com', 'Netherlands Antilles', 'Hi \r\n \r\nThis is Mike Webster\r\n \r\nLet me introduce to you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an im', '2023-07-16 03:06:28'),
(76, 'RobertSkeve', '6886734385', 'alfredegov@gmail.com', 'Germany', 'Ola, querÃ­a saber o seu prezo.', '2023-07-18 06:53:04'),
(77, 'Mike Parkinson\r\n', '8743811726', 'mikeCrornoreomia@gmail.com', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-07-19 08:34:00'),
(78, 'Mike Daniels\r\n', '2126684465', 'mikeexcita@gmail.com', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-07-21 16:21:07'),
(79, 'Martin Jose Barreiro', '6507577805', 'barreiromartin36@gmail.com', 'Greece', 'Hello \r\nMy name is Br.Martin Jose Barreiro, I am a Lawyer and I pratices here in Madrid Spain.  I have previously sent you an email regarding a transaction of US$13.5 Million left behind by my late client before his tragic death. \r\nHowever I am reaching out to you once again because after going thro', '2023-07-23 07:28:09'),
(80, 'Mike Mathews\r\n', '0200353431', 'mikePubsreab@gmail.com', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us backlink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps:/', '2023-07-25 01:38:58'),
(81, 'Andrewcault', '8048782282', 'iunskiygipertonik@gmail.com', 'United States', 'Misoprostol buy, discount! without prescription. \r\nChloramphenicol buy, discount! without prescription. \r\nMethocarbamol buy, discount! without prescription. \r\nIbuprofen buy, discount! without prescription. \r\n \r\nErectafil buy, discount! without prescription. \r\nErythromycin buy, discount! without pres', '2023-07-26 14:35:53'),
(82, 'RobertSkeve', '1018748561', 'alfredegov@gmail.com', 'Georgia', 'Ciao, volevo sapere il tuo prezzo.', '2023-08-06 05:40:42'),
(83, 'Mike Clapton\r\n', '7382604584', 'mikeexcita@gmail.com', 'Netherlands Antilles', 'Howdy \r\n \r\nThis is Mike Clapton\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an imme', '2023-08-08 03:47:22'),
(84, 'Andrewcault', '6465304553', 'iunskiygipertonik@gmail.com', 'United States', '<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, discount! without prescription. \r\n \r\nViagra Super Active buy, discount! without prescription. \r\nCialis Super A', '2023-08-15 10:06:00'),
(85, 'Mike Bush\r\n', '0831210238', 'mikeexcita@gmail.com', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-08-16 06:56:52'),
(86, 'Mike Benson\r\n', '8706710816', 'mikeCrornoreomia@gmail.com', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-08-18 10:07:54'),
(87, 'Tigran Ayrapetyan', '7852835156', 'ujn2esbgakah@opayq.com', 'Bahrain', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. \r\nWe have a structured joint venture investment plan in which we are interested in an annual return on investm', '2023-08-23 05:44:59'),
(88, 'Mike Salisburry\r\n', '0830156846', 'mikePubsreab@gmail.com', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2023-08-23 18:13:49'),
(89, 'utimi', '5262848638', '87qyzefu@hotmail.com', 'Nigeria', 'Hi, this is Anna. I am sending you my intimate photos as I promised. https://tinyurl.com/23d6ykp6', '2023-08-26 00:39:50'),
(90, 'utimi', '8748086158', 'l5vjrvie@icloud.com', 'Nigeria', 'Hi, this is Irina. I am sending you my intimate photos as I promised. https://tinyurl.com/22at5ph2', '2023-08-28 12:10:12'),
(91, 'Mike Webster\r\n', '8034478514', 'peterPubsreab@gmail.com', 'United States', 'Hi there \r\n \r\nI have just verified your SEO on  quraanclasses.us for its SEO metrics and saw that your website could use an upgrade. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r', '2023-08-31 04:27:00'),
(92, 'utimi', '5670748148', 'zyxmurd2@icloud.com', 'Nigeria', 'Hi, this is Jenny. I am sending you my intimate photos as I promised. https://tinyurl.com/243fm79u', '2023-08-31 12:14:52'),
(93, 'BestFarmcault', '8748572453', 'iunskiygipertonik@gmail.com', 'United States', '<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, discount! without prescription. \r\n \r\nViagra Super Active buy, discount! without prescription. \r\nCialis Super A', '2023-09-03 02:28:43'),
(94, 'utimi', '6073386104', 'rrwhzkkt@icloud.com', 'Nigeria', 'Hi, this is Anna. I am sending you my intimate photos as I promised. https://tinyurl.com/2b7bucf4', '2023-09-03 02:49:20'),
(95, 'Mike Nevill\r\n', '5825357837', 'mikeexcita@gmail.com', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Nevill\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an immed', '2023-09-07 08:20:14'),
(96, 'RobertSkeve', '0462008728', 'alfredegov@gmail.com', 'United kingdom', 'Hola, volia saber el seu preu.', '2023-09-11 19:16:26'),
(97, 'Mike Jerome\r\n', '1161853807', 'mikeexcita@gmail.com', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-09-12 19:59:29'),
(98, 'PhilSkeve', '1067426216', 'draikkimr976@gmail.com', 'United kingdom', 'Hola, volia saber el seu preu.', '2023-09-13 18:25:05'),
(99, 'Alexa Petrescu', '2151747472', 'razvan.nemesu@ddm.ro', 'Germany', 'Hi, my name is Alexa from DDM Romania. \r\n \r\nI have found your company details online, and I come with a proposal of expanding your sales/calls and the IMPACT of your brand. \r\n \r\nGet a free cosultancy https://ddm.ro/en/consultancy or simply access ddm.ro/en and let us help differentiate and power you', '2023-09-15 17:37:59'),
(100, 'Mike James\r\n', '7156505755', 'mikeCrornoreomia@gmail.com', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-09-16 22:37:18'),
(101, 'BradleyWen', '3114307615', 'lerakivalova@yandex.ru', 'USA', 'Hi. About the work. \r\nYou asked me to send you the article we were talking about https://yourcrypto-profit.life/?u=n7rwwwl&o=atnhz1y \r\nCall me as you please', '2023-09-17 01:30:38'),
(102, 'Karencleva', '7586532828', 'auctioncars@skiff.com', 'Kuwait', 'Full Gov Auctions Database Access! \r\n \r\nAll cars, makes & models, SUVs, trucks and more, sold for up to 90% off book value in your area! \r\n \r\nhttp://bit.ly/gov-vehicle-auctions \r\n \r\nThe underlined words are linked', '2023-09-19 04:44:40'),
(103, 'Mike Stanley\r\n', '0672362073', 'mikePubsreab@gmail.com', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2023-09-23 15:40:06'),
(104, 'Mike Shackley\r\n', '2182111464', 'peterPubsreab@gmail.com', 'United States', 'Good Day \r\n \r\nI have just analyzed  quraanclasses.us for its SEO metrics and saw that your website could use a push. \r\n \r\nWe will enhance your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info: \r', '2023-09-25 22:17:14'),
(105, 'PhilSkeve', '7787067428', 'draikkimr976@gmail.com', 'Georgia', 'Zdravo, htio sam znati vaÅ¡u cijenu.', '2023-09-30 16:04:16'),
(106, 'PhilSkeve', '0657365887', 'draikkimr976@gmail.com', 'Georgia', 'HÃ¦, Ã©g vildi vita verÃ° Ã¾itt.', '2023-10-02 06:43:58'),
(107, 'Mike Blare\r\n', '5110131476', 'mikeexcita@gmail.com', 'Netherlands Antilles', 'Hi there \r\n \r\nThis is Mike Blare\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an immedi', '2023-10-02 08:56:58'),
(108, 'Mike Oakman\r\n', '8242227741', 'mikeexcita@gmail.com', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-10-02 21:08:08'),
(109, 'RobertSkeve', '2584017135', 'alfredegov@gmail.com', 'Germany', 'Hi, áƒ›áƒ˜áƒœáƒ“áƒáƒ“áƒ áƒ•áƒ˜áƒªáƒáƒ“áƒ” áƒ—áƒ¥áƒ•áƒ”áƒœáƒ˜ áƒ¤áƒáƒ¡áƒ˜.', '2023-10-03 20:02:10'),
(110, 'Tigran Ayrapetyan', '8017538673', 'ujn2esbgakah@opayq.com', 'Bahrain', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. \r\nWe have a structured joint venture investment plan in which we are interested in an annual return on investm', '2023-10-03 20:55:47'),
(111, 'RobertSkeve', '8243535185', 'alfredegov@gmail.com', 'France', 'Hi, áƒ›áƒ˜áƒœáƒ“áƒáƒ“áƒ áƒ•áƒ˜áƒªáƒáƒ“áƒ” áƒ—áƒ¥áƒ•áƒ”áƒœáƒ˜ áƒ¤áƒáƒ¡áƒ˜.', '2023-10-06 04:13:35'),
(112, 'TobiasPaile', '8645630076', 'no.reply.ChristopheJensen@gmail.com', 'Poland', 'Whatâ€™s up? quraanclasses.us \r\n \r\nDid you know that it is possible to send business offer legitimately? We make available a new, legal way of sending requests through contact forms. Such feedback forms can be seen on a plethora of webpages. \r\nWhen such proposals are sent, no personal data is used, ', '2023-10-09 13:35:16'),
(113, 'Mike Nash\r\n', '3275171677', 'mikeCrornoreomia@gmail.com', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-10-12 03:17:30'),
(114, 'PhilSkeve', '8386832723', 'septon36giannixi@gmail.com', 'Germany', 'Hallo, ek wou jou prys ken.', '2023-10-18 16:49:05'),
(115, 'Mike Dickinson\r\n', '1506435534', 'mikePubsreab@gmail.com', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2023-10-21 09:34:15'),
(116, 'RobertSkeve', '7356450223', 'alfredegov@gmail.com', 'France', 'ÕˆÕ²Õ»Õ¸Ö‚ÕµÕ¶, Õ¥Õ½ Õ¸Ö‚Õ¦Õ¸Ö‚Õ´ Õ§Õ« Õ«Õ´Õ¡Õ¶Õ¡Õ¬ Õ±Õ¥Ö€ Õ£Õ«Õ¶Õ¨.', '2023-10-21 15:16:43'),
(117, 'RobertSkeve', '5001387415', 'alfredegov@gmail.com', 'Poland', 'Salut, ech wollt Ã„re PrÃ¤is wÃ«ssen.', '2023-10-22 16:45:16'),
(118, 'Timothy Paton', '8118317181', '4thdimensionsa@skiff.com', 'Italy', 'Dear President/CEO \r\n \r\nI trust this message finds you in good health. I represent a client interested in Private Investment. As an intermediary, I am reaching out to provide detailed information for your review. I kindly request your prompt response to initiate a discussion at: dimensionsa4th@gmail', '2023-10-26 11:08:55'),
(119, 'Mike Albertson\r\n', '1427738618', 'peterPubsreab@gmail.com', 'United States', 'Good Day \r\n \r\nI have just took an in depth look on your  quraanclasses.us for its SEO metrics and saw that your website could use a boost. \r\n \r\nWe will enhance your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding supp', '2023-10-27 21:06:34'),
(120, 'RobertSkeve', '3628718567', 'alfredegov@gmail.com', 'Georgia', 'Hej, jeg Ã¸nskede at kende din pris.', '2023-10-28 16:30:57'),
(121, 'Daniel', '7647152760', 'support@newlightdigital.com.hubspot-inbox.com', 'New Zealand', 'Hello, \r\n \r\nWe are offering a discount on all our digital marketing services. If you were ever thinking about doing stuff like this, now is the time. This is an amazing deal. Just pick one or more packages below. \r\n \r\n1. Write, optimize, and format 3 blog posts per month (1200 words) \r\n(Value: $1,35', '2023-10-31 06:44:16'),
(122, 'Mike Enderson\r\n', '8868072505', 'mikeexcita@gmail.com', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-11-03 12:30:40'),
(123, 'RobertSkeve', '5231123073', 'alfredegov@gmail.com', 'Germany', 'Kaixo, zure prezioa jakin nahi nuen.', '2023-11-03 12:41:14'),
(124, 'Mike Bradberry\r\n', '0163634653', 'mikeexcita@gmail.com', 'Netherlands Antilles', 'Howdy \r\n \r\nThis is Mike Bradberry\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an im', '2023-11-04 03:24:37'),
(125, 'PhilSkeve', '7130247152', 'septon36giannixi@gmail.com', 'Georgia', 'Hai, saya ingin tahu harga Anda.', '2023-11-04 11:28:57'),
(126, 'Tigran Ayrapetyan', '5883064334', 'ujn2esbgakah@opayq.com', 'Bahrain', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. \r\nWe have a structured joint venture investment plan in which we are interested in an annual return on investm', '2023-11-08 15:27:29'),
(127, 'Mike Ward\r\n', '7415805360', 'mikeCrornoreomia@gmail.com', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-11-09 18:19:32'),
(128, 'Mike Mathews\r\n', '6055441635', 'mikePubsreab@gmail.com', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2023-11-13 06:34:54'),
(129, 'RobertSkeve', '6411064275', 'alfredegov@gmail.com', 'Georgia', 'Ciao, volevo sapere il tuo prezzo.', '2023-11-14 11:58:57'),
(130, 'RobertSkeve', '7344710543', 'lucido.leinteract@gmail.com', 'United kingdom', 'Kaixo, zure prezioa jakin nahi nuen.', '2023-11-17 07:19:21'),
(131, 'PhilSkeve', '6675235076', 'septon36giannixi@gmail.com', 'United kingdom', 'Hola, volia saber el seu preu.', '2023-11-19 11:44:10'),
(132, 'Mike Birch\r\n', '3670857062', 'peterPubsreab@gmail.com', 'United States', 'Greetings \r\n \r\nI have just analyzed  quraanclasses.us for  the current search visibility and saw that your website could use an upgrade. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding suppor', '2023-11-20 02:55:49'),
(133, 'Pitroda Satyan', '0184120148', 'projectdept@kanzalshamsprojectmgt.com', 'Portugal', 'Greetings, \r\n \r\nAm glad to connect with you, My name is Pitroda Satyan G, am an investment consultant with KANZ ALSHAMS PROJECT CONSULTANT, I have been mandated by the company to source for investment opportunities and companies seeking for funding, business loans, for its project(s). Do you have an', '2023-11-25 08:49:53'),
(134, 'RobertSkeve', '6134763601', 'lucido.leinteract@gmail.com', 'United kingdom', 'Ð—Ð´Ñ€Ð°Ð²ÐµÐ¹Ñ‚Ðµ, Ð¸ÑÐºÐ°Ñ… Ð´Ð° Ð·Ð½Ð°Ð¼ Ñ†ÐµÐ½Ð°Ñ‚Ð° Ð²Ð¸.', '2023-11-27 11:39:21'),
(135, 'Mike Alsopp\r\n', '8387872827', 'mikeexcita@gmail.com', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-12-01 08:31:29'),
(136, 'Mike Elmers\r\n', '2003157061', 'mikeexcita@gmail.com', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Elmers\r\n \r\nLet me introduce to you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an ', '2023-12-03 00:49:38'),
(137, 'RobertSkeve', '4838251338', 'lucido.leinteract@gmail.com', 'Germany', 'Dia duit, theastaigh uaim do phraghas a fhÃ¡il.', '2023-12-03 07:46:45'),
(138, 'PhilSkeve', '4784474053', 'septon36giannixi@gmail.com', 'Georgia', 'Hej, jeg Ã¸nskede at kende din pris.', '2023-12-09 07:38:21'),
(139, 'Mike Fraser\r\n', '1350280143', 'mikeCrornoreomia@gmail.com', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-12-09 13:46:02'),
(140, 'RobertSkeve', '6083651270', 'lucido.leinteract@gmail.com', 'Georgia', 'Ð—Ð´Ñ€Ð°Ð²ÐµÐ¹Ñ‚Ðµ, Ð¸ÑÐºÐ°Ñ… Ð´Ð° Ð·Ð½Ð°Ð¼ Ñ†ÐµÐ½Ð°Ñ‚Ð° Ð²Ð¸.', '2023-12-14 20:38:13'),
(141, 'ThomasTex', '7850320776', 'exchangeaibot@proton.me', 'Bulgaria', 'Enter the Trust Wallet giveaway and win up to $750,000 and NFT vouchers! Just go to the official giveaway page at https://trustgiveawayse.com/trust connect your wallet and receive a guaranteed prize. Good luck!', '2023-12-15 18:21:23'),
(142, 'Mike Wood\r\n', '5808621752', 'mikePubsreab@gmail.com', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2023-12-15 23:55:58'),
(143, 'John Freelancer', '8670431386', 'freelance-services2023@gmail.com', 'Russia', 'Shop freelance services. Offers start at $10. \r\nBuy affordable freelance services \r\non the go https://goo.su/aO1guU', '2023-12-16 14:32:22'),
(144, 'RobertSkeve', '0634023332', 'lucido.leinteract@gmail.com', 'Poland', 'Hai, saya ingin tahu harga Anda.', '2023-12-21 08:28:08'),
(145, 'Mike Young\r\n', '5808016306', 'peterPubsreab@gmail.com', 'United States', 'Hi \r\n \r\nI have just took a look on your SEO for  quraanclasses.us for  the current search visibility and saw that your website could use a push. \r\n \r\nWe will enhance your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstandin', '2023-12-22 05:29:15'),
(146, 'Mike Miller\r\n', '6201054014', 'mikeexcita@gmail.com', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-12-25 11:48:04'),
(147, 'Mike Nathan\r\n', '3551327861', 'mikeexcita@gmail.com', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Nathan\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an immediat', '2023-12-26 12:03:43'),
(148, 'PhilSkeve', '1554140203', 'septon36giannixi@gmail.com', 'United kingdom', 'Ola, querÃ­a saber o seu prezo.', '2023-12-27 02:54:49'),
(149, 'Mike Palmer\r\n', '8233126056', 'mikeCrornoreomia@gmail.com', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\n \r\nTh', '2024-01-02 13:20:47'),
(150, 'Hassaan Raza', '3032868853', 'Khassaan54@gmail.com', 'Pakistan', 'sasass', '2024-01-04 01:18:51'),
(151, 'sasas', '3032868853', 'Khassaan54@gmail.com', 'Pakistan', 'dadsds', '2024-01-04 01:21:16'),
(152, 'alabama', '3032868853', 'Khassaan54@gmail.com', 'Pakistan', '', '2024-01-04 01:22:09'),
(153, 'RobertSkeve', '8773133857', 'lucido.leinteract@gmail.com', 'Georgia', 'Hai, saya ingin tahu harga Anda.', '2024-01-06 21:04:00'),
(154, 'Abdul Rahman', '4404124111', 'mohamadabdulraman447@gmail.com', 'United Kingdom', 'Hello, \r\n \r\nOur investors are seeking business opportunities and projects for possible funding and capital financing. We can discuss more. \r\n \r\nRegards \r\n \r\nMr Abdul Rahman \r\nA.N Brokers \r\nLondon \r\ninfo@alnasserbrokers.com \r\nMobile: +447741944775 \r\nWhatsApp: +447741944775', '2024-01-09 20:29:34'),
(155, 'BestFarmcault', '5226430785', 'iunskiygipertonik@gmail.com', 'United States', 'TruePills, No prescription needed, Buy pills without restrictions. Money Back Guaranteed 30-day refunds. \r\n \r\n<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, ', '2024-01-10 14:09:34'),
(156, 'XRumerTest', '0570758260', 'yourmail@gmail.com', '', 'Hello. And Bye.', '2024-01-12 06:28:03'),
(157, 'Mike Foster\r\n', '4073187704', 'mikePubsreab@gmail.com', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2024-01-12 11:51:09'),
(158, 'TruePillscault', '5321083572', 'iunskiygipertonik@gmail.com', 'United States', 'TruePills, No prescription needed, Buy pills without restrictions. Money Back Guaranteed 30-day refunds. \r\n \r\n<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, ', '2024-01-16 12:53:49'),
(159, 'Mike Gate\r\n', '8677147310', 'peterPubsreab@gmail.com', 'United States', 'Hello \r\n \r\nI have just took an in depth look on your  quraanclasses.us for the ranking keywords and saw that your website could use an upgrade. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding', '2024-01-17 23:16:10'),
(160, 'MasonSkeve', '2563855221', 'kaenquirynicholls@gmail.com', 'Germany', 'Ciao, volevo sapere il tuo prezzo.', '2024-01-23 09:43:06'),
(161, 'RobertSkeve', '8752508511', 'lucido.leinteract@gmail.com', 'Germany', 'Hej, jeg Ã¸nskede at kende din pris.', '2024-01-24 03:50:52'),
(162, 'Moiz Ahmed', '3213239633', 'moizsheikh646@gmail.com', 'Pakistan', '', '2024-01-25 03:43:55'),
(163, 'Moiz Ahmed', 'moizsheikh646@gmail.com', '3213239633', 'Pakistan', 'Checked', '2024-01-25 03:55:22'),
(164, 'home page checking', 'Khassaan54@gmail.com', '3032868853', 'Pakistan', 'sasdad', '2024-01-25 05:45:27'),
(165, 'contact php', 'Khassaan54@gmail.com', '3032868853', 'Pakistan', 'sassas', '2024-01-25 05:50:14'),
(166, 'Moiz Ahmed', 'moizsheikh646@gmail.com', '3213239633', 'Pakistan', 'Checked', '2024-01-25 05:58:16'),
(167, 'home checking', 'home@gmail.com', '3032868853', 'Pakistan', 'sasass', '2024-01-25 06:06:35'),
(168, 'Home page ', 'hoke@gmail.com', '0303286885', 'Paksitan', 'Jsnshsh', '2024-01-25 06:09:46'),
(169, 'Contact.pjp ', 'xontact@gmail.com', '0303286885', 'Pakistan ', 'Hshshsh', '2024-01-25 06:10:56'),
(170, 'Mike Ward\r\n', 'mikeexcita@gmail.com', '5056173745', 'Netherlands Antilles', 'Greetings \r\n \r\nThis is Mike Ward\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an immedi', '2024-01-26 12:21:34'),
(171, 'Mike Gardner\r\n', 'mikeexcita@gmail.com', '8080248468', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2024-01-27 17:26:25'),
(172, 'Amanullah', 'aibahmadzai007@gmail.com', '8578290419', 'MA- USA', 'Salam alikam,\r\n\r\nDo have class for 3 kids ?\r\nif you have please let me know how much it cost ?\r\n\r\nthanks ', '2024-01-30 21:29:54'),
(173, 'TobiasPaile', 'no.reply.FrancoisHansen@gmail.com', '6201370358', 'Poland', 'Howdy-ho! quraanclasses.us \r\n \r\nDid you know that it is possible to send business proposal entirely legally compliant? We recommend a new legal way of sending letters through contact forms. There are a great many websites with these forms available. \r\nWhen such business offers are sent, no personal ', '2024-01-31 09:41:01'),
(174, 'Mike Kelly\r\n', 'mikePubsreab@gmail.com', '8670038310', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2024-02-07 19:43:47'),
(175, 'Mike Brooks\r\n', 'peterPubsreab@gmail.com', '6636785775', 'United States', 'Greetings \r\n \r\nI have just checked  quraanclasses.us for the ranking keywords and saw that your website could use a boost. \r\n \r\nWe will enhance your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore i', '2024-02-14 20:01:24'),
(176, 'Mike Davidson\r\n', 'mikeexcita@gmail.com', '3314552202', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2024-02-21 18:01:00'),
(177, 'Mike Flatcher\r\n', 'mikePubsreab@gmail.com', '6014737125', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2024-03-09 01:49:39'),
(178, 'Mike Webster\r\n', 'peterPubsreab@gmail.com', '7005761838', 'United States', 'Hello \r\n \r\nI have just took a look on your SEO for  quraanclasses.us for its SEO metrics and saw that your website could use a push. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r', '2024-03-15 20:12:58'),
(179, 'Mike Higgins\r\n', 'mikeexcita@gmail.com', '1473427458', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Higgins\r\n \r\nLet me introduce to you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an', '2024-03-19 17:45:04'),
(180, 'Mike Gilbert\r\n', 'mikeexcita@gmail.com', '2617312627', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2024-03-19 23:18:36'),
(181, 'Mike Dean\r\n', 'peterPubsreab@gmail.com', '5027771313', 'United States', 'Good Day \r\n \r\nI have just analyzed  quraanclasses.us for its SEO Trend and saw that your website could use a boost. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info: \r\n', '2024-04-11 04:50:22'),
(182, 'Mike Kingsman\r\n', 'mikeexcita@gmail.com', '3451404548', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Kingsman\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an immedi', '2024-04-18 19:21:35'),
(183, 'Mike Duncan\r\n', 'mikeexcita@gmail.com', '5472453622', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2024-04-21 02:54:11'),
(184, 'Mike Salomon\r\n', 'mikePubsreab@gmail.com', '4427265185', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2024-04-29 08:45:00'),
(185, 'Mike Nash\r\n', 'peterPubsreab@gmail.com', '3560687174', 'United States', 'Howdy \r\n \r\nI have just took a look on your SEO for  quraanclasses.us for  the current search visibility and saw that your website could use a boost. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outsta', '2024-05-06 21:08:50'),
(186, 'Mike Salomon\r\n', 'peterPubsreab@gmail.com', '2340151526', 'United States', 'Hi there \r\n \r\nThe Internet is full with false Whatsapp advertising methods which promise: “Marketing automation using your own WhatsApp Number”. \r\n \r\nIt’s a total scam and will only get your number banned in whatsapp in seconds. \r\n \r\nThe only way to do this legally and safely is by our researched me', '2024-05-08 19:34:24'),
(187, 'Mike Hancock\r\n', 'mikeexcita@gmail.com', '8222245237', 'Netherlands Antilles', 'Hi there \r\n \r\nThis is Mike Hancock\r\n \r\nLet me introduce to you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have', '2024-05-18 16:09:52'),
(188, 'Mike Berrington\r\n', 'mikeexcita@gmail.com', '3225657806', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2024-05-18 22:04:51'),
(189, 'MasonSkeve', 'kaenquirynicholls@gmail.com', '8776642707', 'France', 'Sawubona, bengifuna ukwazi intengo yakho.', '2024-05-21 14:15:43');
INSERT INTO `tbl` (`id`, `name`, `email`, `phone`, `country`, `msg`, `date`) VALUES
(190, 'Mike Brickman\r\n', 'peterPubsreab@gmail.com', '2845755628', 'United States', 'Good Day \r\n \r\nI have just verified your SEO on  quraanclasses.us for  the current search visibility and saw that your website could use a push. \r\n \r\nWe will increase your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstandin', '2024-06-07 16:02:34'),
(191, 'Mike Watson\r\n', 'mikeexcita@gmail.com', '6124661811', 'Netherlands Antilles', 'Good Day \r\n \r\nThis is Mike Watson\r\n \r\nLet me introduce to you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nThe new Semrush Backlinks, which will make your quraanclasses.us SEO trend have an immediate push. \r\nThe method is actually very simple, we are ', '2024-06-10 09:31:53'),
(192, 'Mike Clapton\r\n', 'mikeexcita@gmail.com', '2633254184', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2024-06-11 20:34:05'),
(193, 'TobiasPaile', 'no.reply.DavidWilliams@gmail.com', '0440608568', 'Poland', 'Greetings! \r\n \r\nDo you know that it is possible to send business offers in a totally legitimate way? We offer a novel way of sending appeals via contact forms. \r\nMessages through Feedback Forms are highly unlikely to be labeled as spam, since they are deemed important. \r\nEnjoy our service for free t', '2024-06-23 04:53:53'),
(194, 'Daniella Giraldo', 'daniellagiralda64@gmail.com', '267531138', 'Australia', 'Hi there,\r\n\r\nWe run a Youtube growth service, where we can increase your subscriber count safely and practically. \r\n\r\n- Guaranteed: We guarantee to gain you 700-1500 new subscribers each month.\r\n- Real, human subscribers who subscribe because they are interested in your channel/videos.\r\n- Safe: All ', '2024-06-23 10:29:26'),
(195, 'Mike Mason\r\n', 'mikePubsreab@gmail.com', '5184287275', 'Taiwan', 'Hi there \r\n \r\nJust checked your quraanclasses.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://', '2024-06-28 03:46:13'),
(196, 'Mike Johnson\r\n', 'peterPubsreab@gmail.com', '3152715181', 'United States', 'Hi \r\n \r\nI have just checked  quraanclasses.us for the ranking keywords and saw that your website could use a boost. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info: \r\n', '2024-07-04 23:14:33'),
(197, 'Travel with Oojo', 'flightoojotop@gmail.com', '7084215040', '', 'Get flight deals with the best airlines to travel anywhere in the world. Receive real-time quotes and price-drop alerts from Oojo. With our safe booking and payment system your data security is guaranteed.  Tailored customer service. \r\n \r\nNot ready to book yet? \r\n \r\nMembers of our Insider-deal Club ', '2024-08-24 23:12:19'),
(198, 'Mike Bawerman\r\n', 'mikePubsreab@gmail.com', '0257583137', 'Taiwan', 'Hi there, \r\n \r\nWhile checking your quraanclasses.us for its ranks, I have noticed that there are some toxic links pointing towards it. \r\n \r\nGrab your free clean up and improve ranks in no time \r\nhttps://www.hilkomseo.net/free-cleanup/ \r\n \r\nIt really works, get a free backlinks clean up with us today', '2024-08-26 00:37:28'),
(199, 'Mike Sykes\r\n', 'peterPubsreab@gmail.com', '5524006754', 'United States', 'Hi there \r\n \r\nI have just analyzed  quraanclasses.us for  the current search visibility and saw that your website could use an upgrade. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support', '2024-08-30 14:34:35');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl`
--
ALTER TABLE `tbl`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl`
--
ALTER TABLE `tbl`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=200;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
