-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 17, 2024 at 10:09 AM
-- Server version: 10.6.19-MariaDB-cll-lve
-- PHP Version: 8.1.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `qurascxb_learnquraanus`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl`
--

CREATE TABLE `tbl` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `phone` varchar(15) NOT NULL,
  `country` varchar(50) NOT NULL,
  `msg` varchar(300) NOT NULL,
  `date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `tbl`
--

INSERT INTO `tbl` (`id`, `name`, `email`, `phone`, `country`, `msg`, `date`) VALUES
(4, 'Moiz Ahmed ', '0321323963', 'moizsheikh646@g', 'pakistan', 'checked', '2023-03-10 02:10:17'),
(5, 'Moiz Ahmed ', '0321323963', 'moizsheikh646@g', 'pakistan', 'sdfggh', '2023-03-10 02:11:39'),
(6, 'Hassaan ', 'hassaan@yahoo.om', '7339838383', 'Pakistan ', '', '2023-03-11 04:25:40'),
(7, 'Moiz Ahmed', 'moizsheikh646@gmail.com', '0321323963', 'Pakistan', 'Checked', '2023-03-11 04:26:01'),
(8, 'Mike Webster\r\n', 'no-replybleaway@gmail.com', '4638672800', 'New Zealand', 'If you have a local business and want to rank it on google maps in a specific area then this service is for you. \r\n \r\nGoogle Map Stacking is one of the best ways to rank your GMB in a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThanks and Rega', '2023-03-14 03:36:22'),
(9, 'Sean Delanpi', 'seandelanpi@seandelanpi.com', '2644523061', 'Italy', 'Good day \r\n \r\nI reached out to you few days ago seeking your cooperation in a matter relating to funds worth $24 Million, please get immediate. \r\n \r\nI await your response, \r\nSeandelanpi1@seandelanpi.com \r\nThanks, \r\n \r\nSean Delanpi', '2023-03-14 16:04:38'),
(10, 'fasd', 'raheemsiddiqui2002@gmail.com', '1234567892', 'pakistabn', 'hngchjg', '2023-03-22 06:00:16'),
(11, 'alabama', 'raheemsiddiqui2002@gmail.com', '1234567892', 'pakistabn', 'iuiuy', '2023-03-22 06:56:39'),
(12, 'Home page ', 'home.php@gmail.com', '3032868853', 'Pakistan', 'home page checking', '2023-03-23 18:09:16'),
(13, 'contact.php', 'contact.php@gmail.com', '3032868853', 'Pakistan', '', '2023-03-23 18:11:00'),
(14, 'Hassaan Raza', 'Khassaan54@gmail.com', '3032868853', 'Pakistan', 'phoenix', '2023-03-23 18:14:05'),
(15, 'Mike Longman\r\n', 'no-replybleaway@gmail.com', '3732512243', 'Taiwan', 'Hi \r\n \r\nI have just checked  learnquraan.us for its SEO Trend and saw that your website could use a push. \r\n \r\nWe will enhance your ranks organically and safely, using state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info: \r\nhttps://www.hil', '2023-03-26 10:33:42'),
(16, 'Mike Smith\r\n', 'no-replybleaway@gmail.com', '1680616028', 'United States', 'Hi \r\n \r\nI have just took an in depth look on your  learnquraan.us for onsite errors and saw that your website has a handful of issues which should be addressed. \r\n \r\nNo matter what you are offering or selling, having a poor optimized site, full of bugs and errors, will never help your ranks. \r\n \r\nLe', '2023-03-31 23:14:48'),
(17, 'Mike Livingston\r\n', 'no-replybleaway@gmail.com', '4220053070', 'Netherlands Antilles', 'Hi there \r\n \r\nThis is Mike Livingston\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an ', '2023-04-03 03:53:05'),
(18, 'alabama', 'moiz@gmail.com', '1234567892', 'pakistabn', 'fsdf', '2023-04-03 04:28:53'),
(19, 'AnikaPl', 'anikaPl@remotelyonboard.com', '3325827164', 'Czechia', 'ÐÐµllÐ¾Çƒ\r\nPÐµrhaÑ€s my messÐ°ge is tÐ¾Ð¾ Ñ•pÐµÑÑ–fÑ–Ñ.\r\nÎ’ut mÑƒ older sÑ–Ñ•tÐµr found a wonderful man hÐµre Ð°nd they havÐµ a great rÐµlÐ°tionshÑ–p, but whÐ°t about me?\r\nI am 28 ÑƒÐµarÑ• old, AnÑ–ka, from thÐµ Czech RÐµpublÑ–c, know Ð•nglish lÐ°nguÐ°gÐµ Ð°lso\r\nÎ‘nd... better tÐ¾ Ñ•aÑƒ Ñ–t immed', '2023-04-03 05:33:22'),
(20, 'Mike Bawerman\r\n', 'no-replybleaway@gmail.com', '2745076248', 'United States', 'Hi there \r\n \r\nJust checked your learnquraan.us in MOZ and saw that you could use an authority boost. \r\n \r\nWith our service you will get a guaranteed Domain Authority score within just 3 months time. This will increase the organic visibility and strengthen your website authority, thus getting it stro', '2023-04-06 03:34:53'),
(21, 'Catherinajiz', 'catherinajiz@myedoor.com', '6827278124', 'Romania', 'Hello all, guÑƒÑ•! Î™ knÐ¾w, mÑƒ mesÑ•agÐµ mÐ°y be tÐ¾Ð¾ Ñ•pÐµcÑ–fÑ–c,\r\nÐ’ut mÑƒ sister found niÑe mÐ°n here and thÐµy marrÑ–ed, sÐ¾ how abÐ¾ut mÐµ?! :)\r\nI am 24 ÑƒearÑ• Ð¾ld, Ð¡athÐµrÑ–na, from Romania, Î™ know Î•ngliÑ•h Ð°nd GÐµrman languÐ°gÐµs also\r\nAnd... I hÐ°ve specÑ–fÑ–Ñ dÑ–sÐµÐ°se, namÐµd ', '2023-04-10 17:27:38'),
(22, 'Mike Davis\r\n', 'no-replybleaway@gmail.com', '0747454114', 'New Zealand', 'If you have a local business and want to rank it on google maps in a specific area then this service is for you. \r\n \r\nGoogle Map Stacking is one of the best ways to rank your GMB in a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThanks and Rega', '2023-04-14 14:29:34'),
(23, 'Mike Laird\r\n', 'no-replybleaway@gmail.com', '5245673058', 'Taiwan', 'Howdy \r\n \r\nI have just took a look on your SEO for  learnquraan.us for the ranking keywords and saw that your website could use an upgrade. \r\n \r\nWe will enhance your ranks organically and safely, using state of the art AI and whitehat methods, while providing monthly reports and outstanding support.', '2023-04-21 09:48:54'),
(24, 'Daniel', 'support@newlightdigital.com.hubspot-inbox.com', '3743364055', 'Canada', 'Hi there, \r\n \r\nUse this checklist to see if your website meets the minimum user experience requirements to rank on Google: \r\n \r\nhttps://newlightdigital.com/25-point-website-usability-checklist/ \r\n \r\nIf you are coming short, or not sure, just reach out to us for a free evaluation of your website. \r\n ', '2023-05-03 03:26:23'),
(25, 'Mike Larkins\r\n', 'no-replybleaway@gmail.com', '8650375184', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Larkins\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immedi', '2023-05-05 06:13:24'),
(26, 'Mike Cooper\r\n', 'no-replybleaway@gmail.com', '3668300876', 'United States', 'Hi there \r\n \r\nJust checked your learnquraan.us in MOZ and saw that you could use an authority boost. \r\n \r\nWith our service you will get a guaranteed Domain Authority score within just 3 months time. This will increase the organic visibility and strengthen your website authority, thus getting it stro', '2023-05-07 13:42:35'),
(27, 'Mike Morrison\r\n', 'no-replybleaway@gmail.com', '2823745482', 'Taiwan', 'Hi there \r\n \r\nI have just checked  learnquraan.us for the ranking keywords and saw that your website could use an upgrade. \r\n \r\nWe will improve your ranks organically and safely, using state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info: ', '2023-05-20 17:56:17'),
(28, 'Waheed Mohammed', 'ujn2esbgakah@opayq.com', '0813271541', 'Portugal', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. We have a structured joint venture investment plan in which we are interested in an annual return on investmen', '2023-05-25 03:25:37'),
(29, 'ODOZIAKUCHI', 'hello@odoziakuchi.com', '4872253812', 'Italy', 'Good day! \r\n \r\nLooking for Heirloom fine Jewellery? \r\n \r\nODOZIAKUCHI is an exciting jewellery brand that celebrates individuality, our mission is to create sentimental jewellery with meaning that move on to become heirlooms for generations. \r\n \r\nWe pride ourselves in making sustainable timeless jewe', '2023-06-01 21:04:13'),
(30, 'Mike MacDonald\r\n', 'no-replybleaway@gmail.com', '5405105133', 'Netherlands Antilles', 'Good Day \r\n \r\nThis is Mike MacDonald\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an i', '2023-06-02 12:30:45'),
(31, 'Michaelcam', 'support1@sparkweb.vip', '7603375166', 'Virgin Islands', 'We are a software outsourcing company from China, if you have any software customization or it technical service needs can contact us, if you need a long-term technical team to develop and maintain different projects for you, we will be your best choice, we will cooperate with your time zone, 7 * 24', '2023-06-08 01:09:35'),
(32, 'Susan Karsh', 'susankarsh.myaa@gmail.com', '3538744865', 'New Zealand', 'Hello, \r\n \r\nI was on your site today and I wanted to see if you would be open to getting a FREE 14-Day trial of our AI Agents, like ChatGPT, but much better. Plus, our plans start at just $1 per month if you decide to continue. \r\n \r\nOur AI Agents Can: \r\n \r\nâ€¢	Assist your team with tasks, projects a', '2023-06-08 13:54:22'),
(33, 'Mike Hardman\r\n', 'no-replybleaway@gmail.com', '6327728006', 'New Zealand', 'If you have a local business and want to rank it on google maps in a specific area then this service is for you. \r\n \r\nGoogle Map Stacking is one of the best ways to rank your GMB in a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThanks and Rega', '2023-06-08 18:01:44'),
(34, 'Tigran Ayrapetyan', 'ujn2esbgakah@opayq.com', '4582136126', 'Bahrain', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. \r\nWe have a structured joint venture investment plan in which we are interested in an annual return on investm', '2023-06-14 10:55:37'),
(35, 'Mike Hailey\r\n', 'no-replybleaway@gmail.com', '1271801114', 'Taiwan', 'Hello \r\n \r\nI have just took a look on your SEO for  learnquraan.us for the ranking keywords and saw that your website could use a boost. \r\n \r\nWe will improve your ranks organically and safely, using state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n', '2023-06-14 21:58:45'),
(36, 'Mike MacAdam\r\n', 'no-replybleaway@gmail.com', '8425413374', 'United States', 'Hi there \r\n \r\nI have just took an in depth look on your  learnquraan.us for the current onsite SEO status and saw that your website has a handful of issues which should be addressed. \r\n \r\nNo matter what you are offering or selling, having a poor optimized site, full of bugs and errors, will never he', '2023-06-24 00:47:50'),
(37, 'Mike Peacock\r\n', 'no-replybleaway@gmail.com', '5841028403', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-06-27 05:19:04'),
(38, 'Susan Karsh', 'susankarsh.myaa@gmail.com', '5382455386', 'Germany', 'Hello, \r\n \r\nI was on your site today and I wanted to see if you would be open to getting a FREE 14-Day trial of our AI Agents, like ChatGPT, but much better. Plus, our plans start at just $1 per month if you decide to continue. \r\n \r\nOur AI Agents Can: \r\n \r\nâ€¢	Assist your team with tasks, projects a', '2023-06-27 18:33:55'),
(39, 'Mike Marshman\r\n', 'mikebleaway@gmail.com', '4677506583', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Marshman\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immediat', '2023-06-30 15:25:52'),
(40, 'Andrewdyday', 'iunskiygipertonik@gmail.com', '1841703274', 'United States', 'Udenafil buy, discount! without prescription. \r\nMometasone buy, discount! without prescription. \r\nEthinyl buy, discount! without prescription. \r\nDrospirenone buy, discount! without prescription. \r\n \r\nOmnicef buy, discount! without prescription. \r\nZyprexa buy, discount! without prescription. \r\nDiltia', '2023-07-03 23:11:12'),
(41, 'RobertAcise', 'alfredegov@gmail.com', '5288324840', 'France', 'Hej, jeg Ã¸nskede at kende din pris.', '2023-07-18 23:34:37'),
(42, 'Peter Gill\r\n', 'petersweammods@gmail.com', '6600126840', 'United States', 'Hi there \r\n \r\nWhat if you could grab all the possible resources that your competitors rank with. \r\n \r\nOur competition search strategy will examine tens of millions of backlinks to find available resources that all your major rivals possess, and then use them to your advantage. \r\n \r\nGet your site to ', '2023-07-23 11:00:24'),
(43, 'Martin Jose Barreiro', 'barreiromartin36@gmail.com', '8848864331', 'Greece', 'Hello \r\nMy name is Br.Martin Jose Barreiro, I am a Lawyer and I pratices here in Madrid Spain.  I have previously sent you an email regarding a transaction of US$13.5 Million left behind by my late client before his tragic death. \r\nHowever I am reaching out to you once again because after going thro', '2023-07-24 20:54:24'),
(44, 'Mike Youmans\r\n', 'mikeloobollemy@gmail.com', '0434814381', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-07-25 06:37:53'),
(45, 'Andrewdyday', 'iunskiygipertonik@gmail.com', '5364652750', 'United States', 'Ethinyloestradiol buy, discount! without prescription. \r\nEstradiol buy, discount! without prescription. \r\nCabergoline buy, discount! without prescription. \r\nSalmeterol buy, discount! without prescription. \r\n \r\nWellbutrin buy, discount! without prescription. \r\nXeloda buy, discount! without prescripti', '2023-07-26 11:45:46'),
(46, 'Mike Timmons\r\n', 'mikebleaway@gmail.com', '5385064845', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Timmons\r\n \r\nLet me introduce to you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an i', '2023-07-28 03:32:27'),
(47, 'Mike Clapton\r\n', 'mikeAvannecreaphtync@gmail.com', '8750352548', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-08-01 13:29:39'),
(48, 'Ð”Ð¾cÑ‚ÑƒÐ¿ Ðº ÑƒcÐ¿eÑˆÐ½Ñ‹Ð¼ uÐ½Ð²ÐµcÑ‚uÑ†Ð¸ÑÐ¼ ', 'crotdiasu1987+7@mail.ru', '7302782166', 'Ð Â Ð Ñ•Ð¡ÐƒÐ¡ÐƒÐ Ñ‘Ð¡Ð', '', '2023-08-02 20:39:51'),
(49, 'RobertAcise', 'alfredegov@gmail.com', '6737763715', 'Germany', 'Hej, jeg Ã¸nskede at kende din pris.', '2023-08-06 22:31:36'),
(50, 'T6QM GwHOh Ð”Ð¾cÑ‚ÑƒÐ¿ Ðº kpÑƒÐ¿Ð½Ð¾Ð¼Ñƒ Ð¿Ñ€Ð¸Ð²Ð', 'credwale1987+1@mail.ru', '8735055664', 'Ð Â Ð Ñ•Ð¡ÐƒÐ¡ÐƒÐ Ñ‘Ð¡Ð', '', '2023-08-10 14:55:53'),
(51, 'Stevenfat', 'sudogo7788@ro.ru', '4274132683', 'Sierra Leone', ' \r\nÐ‘Ð°Ð³Ð°Ñ‚ÑŒÐ¾Ñ… Ð³ÑƒÑ€Ð¼Ð°Ð½Ñ–Ð²  Ñ†Ñ–ÐºÐ°Ð²Ð¸Ñ‚ÑŒ <a href=https://ego-forni.com/>Ð¿Ñ–Ñ†Ð° Ð½Ð° Ð´Ñ€Ð¾Ð²Ð°Ñ…</a>. Ð”Ð»Ñ Ñ†ÑŒÐ¾Ð³Ð¾ Ð¿Ð¾Ñ‚Ñ€Ñ–Ð±Ð½Ð° \r\n<a href=https://ego-forni.com/>Ð¿Ñ–Ñ‡ Ð´Ð»Ñ Ð¿Ñ–Ñ†Ð¸</a>. 	 \r\nÐ¢Ð°ÐºÐ¾Ð¶ ÑÐ²Ð¾Ñ—Ð¼Ð¸ Ð²Ð»Ð°ÑÑ‚Ð¸Ð²Ð¾ÑÑ‚ÑÐ¼Ð¸ Ñ– ÑÐºÑ–ÑÑ‚ÑŽ Ð²Ð¸Ð´Ñ–Ð»ÑÑ”Ñ', '2023-08-12 16:53:37'),
(52, 'Mike Dutton\r\n', 'miketync@gmail.com', '6430246658', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2023-08-12 21:38:34'),
(53, 'BestFarmdyday', 'iunskiygipertonik@gmail.com', '5231172830', 'United States', '<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, discount! without prescription. \r\n \r\nViagra Super Active buy, discount! without prescription. \r\nCialis Super A', '2023-08-13 18:50:10'),
(54, 'Andrewdyday', 'iunskiygipertonik@gmail.com', '7313800177', 'United States', '<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, discount! without prescription. \r\n \r\nViagra Super Active buy, discount! without prescription. \r\nCialis Super A', '2023-08-15 07:15:39'),
(55, 'Mike Douglas\r\n', 'petersweammods@gmail.com', '5254680061', 'United States', 'Hi there \r\n \r\nI have just took an in depth look on your  learnquraan.us for the ranking keywords and saw that your website could use a boost. \r\n \r\nWe will enhance your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding s', '2023-08-16 12:10:01'),
(56, 'Mike Albertson\r\n', 'mikeloobollemy@gmail.com', '2365103452', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-08-23 06:05:22'),
(57, 'Josephfus', 'yasen.krasen.13+82049@mail.ru', '2041723877', 'Canada', 'Mfhfujfehfueh ifwjifjeighufijsdh uidfsjkdokwefuhgedjij idoweweureiurioweiidkjsdj iwjdsksosjfeihfiwskdoakd ijwdiwdowjfihefiwjdiwhfgue learnquraan.us', '2023-08-24 15:35:30'),
(58, 'Mike Wainwright\r\n', 'mikebleaway@gmail.com', '5151627250', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Wainwright\r\n \r\nLet me introduce to you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have a', '2023-08-24 23:54:43'),
(59, 'Waynewed', 'arabinvestment354@gmail.com', '4422268833', 'Austria', 'We offer loans on investment basis @ a mere 3% interest rate for \r\namounts of up to $800MM for duration of 30 years! If you are \r\ninterested please email: loanagent@arabiinvestment.com', '2023-08-25 23:24:16'),
(60, 'SaP', '67bv2y34@gmail.com', '8810830714', 'Nigeria', 'Hi, this is Anna. I am sending you my intimate photos as I promised. https://tinyurl.com/24hj9qrk', '2023-08-26 20:54:39'),
(61, 'Mike Faber\r\n', 'mikeAvannecreaphtync@gmail.com', '3338313875', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-08-29 22:46:36'),
(62, 'Scottkeync', 'jonestax7@yahoo.com', '4580540238', 'Luxembourg', 'Get 3100 High Quality Backlinks and Rank TOP 10 Google http://free-backlinks-1592.janoub-hightech.com/exclusive', '2023-08-30 19:00:20'),
(63, 'Douglasted', 'elisagreco746@gmail.com', '4434328736', 'United Kingdom', 'EARN $100000 PER WEEK OR MORE WITH FOREX http://earn-money-forex-5111.zahiradiaz.com/product', '2023-08-31 14:12:02'),
(64, 'Douglasted', 'jonny1560@hotmail.it', '2070517621', 'United Kingdom', 'EARN $100000 PER WEEK OR MORE WITH FOREX http://earn-forex-4032.elisou.com/product', '2023-09-02 18:36:04'),
(65, 'BestFarmdyday', 'iunskiygipertonik@gmail.com', '5030327125', 'United States', '<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, discount! without prescription. \r\n \r\nViagra Super Active buy, discount! without prescription. \r\nCialis Super A', '2023-09-03 00:34:23'),
(66, 'Mike Moore\r\n', 'miketync@gmail.com', '3130852282', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2023-09-06 21:34:36'),
(67, 'RobertoresE', 'sherlyn@yahoo.com', '6887266527', 'United States', 'ARCHIVAL EXCLUSIVE PHOTOS OF NAKED KIM KARDASHIAN - 34 PHOTOS http://naked-kim-71022.omtogelprediksi.com/site', '2023-09-09 01:13:56'),
(68, 'KennethUrIne', 'dbenois@teppich-huus-breiti.ch', '1170310527', 'Norway', 'Generate cryptocurrency out of thin air up to $900 per day https://offlimit-co-dot-yamm-track.appspot.com/Redirect?ukey=1bFe2zxsQN1oGpoXcZXkNGW_bAqcW6Ur8aQDFBCryE2I-416397258&key=YAMMID-31247829&link=https%3A%2F%2Fseoshopbacklinks.sell.app%2Fproduct%2Fcheat-code-how-to-generate-cryptocurrency-out-of', '2023-09-11 11:44:10'),
(69, 'RobertAcise', 'alfredegov@gmail.com', '6628474551', 'France', 'Sveiki, es gribÄ“ju zinÄt savu cenu.', '2023-09-12 11:30:25'),
(70, 'Brandontak', 'elenazanetti@rocketmail.com', '5280033741', 'Denmark', 'I earned 12600 BTC in 9 months http://12600-bitcoin-11461.harpersbazaars.com/new', '2023-09-12 11:55:40'),
(71, 'JoshuaEruro', 'alberthasmoons789@binace.com', '2736717056', 'Denmark', 'Hello. \r\nYou registered with us exactly 364 days ago, but for some reason you never logged into your account again. \r\nYour account has already accumulated $24,365 - withdraw it urgently. Since tomorrow all inactive accounts will be deleted along with all the money earned. \r\nThere was no way we could', '2023-09-13 13:19:21'),
(72, 'PhilAcise', 'draikkimr976@gmail.com', '7642048316', 'Georgia', 'Hi, kam dashur tÃ« di Ã§mimin tuaj', '2023-09-14 12:19:09'),
(73, 'Mike Ayrton\r\n', 'petersweammods@gmail.com', '8300423655', 'United States', 'Greetings \r\n \r\nI have just analyzed  learnquraan.us for its SEO Trend and saw that your website could use an upgrade. \r\n \r\nWe will increase your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info:', '2023-09-16 08:25:10'),
(74, 'Bradleybuh', 'lerakivalova@yandex.ru', '6581484217', 'USA', 'Hi. About the work. \r\nYou asked me to send you the article we were talking about https://yourcrypto-profit.life/?u=n7rwwwl&o=atnhz1y \r\nCall me as you please', '2023-09-16 13:01:00'),
(75, 'Tigran Ayrapetyan', 'ujn2esbgakah@opayq.com', '0481323188', 'Bahrain', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. \r\nWe have a structured joint venture investment plan in which we are interested in an annual return on investm', '2023-09-17 17:30:43'),
(76, 'Mike Higgins\r\n', 'mikeloobollemy@gmail.com', '6066428647', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-09-18 09:13:48'),
(77, 'Andremail', 'yourmail@gmail.com', '4456868720', '', 'Hello. I will increase your sales through mass mailings. I guarantee anonymity and quality. Moderate prices and high returns. I am aimed at long-term cooperation. I work with different countries. Very great experience. \r\n \r\nI deal with the following types of mailings: e-mail mailings, mailings via i', '2023-09-22 12:53:26'),
(78, 'Mike Edwards\r\n', 'mikebleaway@gmail.com', '8156515813', 'Netherlands Antilles', 'Good Day \r\n \r\nThis is Mike Edwards\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immedi', '2023-09-22 19:43:14'),
(79, 'Mike Kennett\r\n', 'mikeAvannecreaphtync@gmail.com', '7082556041', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-09-28 04:47:35'),
(80, 'Rogerlip', 'Gabrieltapia@me.com', '6473285067', 'Iceland', 'URGENT MESSAGE! Quick income of exactly $1000 per day on cryptocurrency http://earn-511691.apbet998.com/click', '2023-09-28 13:26:22'),
(81, 'PhilAcise', 'draikkimr976@gmail.com', '3083478688', 'Germany', 'Ð—Ð´Ñ€Ð°Ð²ÐµÐ¹Ñ‚Ðµ, Ð¸ÑÐºÐ°Ñ… Ð´Ð° Ð·Ð½Ð°Ð¼ Ñ†ÐµÐ½Ð°Ñ‚Ð° Ð²Ð¸.', '2023-10-01 07:48:33'),
(82, 'AnnaGex', 'annaGex@onlinejobsusa.com', '1216174346', 'Czechia', 'HÐµllÐ¾Çƒ\r\nI aÑ€Ð¾lÐ¾gÑ–zÐµ for the overly Ñ•pÐµcÑ–fÑ–Ñ meÑ•sagÐµ.\r\nMy girlfriend Ð°nd Î™ love ÐµÐ°ch Ð¾ther. And we Ð°rÐµ Ð°ll greÐ°t.\r\nBut... we need Ð° mÐ°n.\r\nWÐµ are 26 ÑƒÐµÐ°rÑ• old, frÐ¾m RÐ¾mÐ°nia, wÐµ alÑ•Ð¾ knÐ¾w ÐµnglÑ–sh.\r\nWe never get bÐ¾rÐµd! Î‘nd nÐ¾t Ð¾nlÑƒ in talk...\r\nÎœÑƒ namÐµ is ', '2023-10-02 12:15:44'),
(83, 'PhilAcise', 'draikkimr976@gmail.com', '2671738330', 'Georgia', 'Hi, áƒ›áƒ˜áƒœáƒ“áƒáƒ“áƒ áƒ•áƒ˜áƒªáƒáƒ“áƒ” áƒ—áƒ¥áƒ•áƒ”áƒœáƒ˜ áƒ¤áƒáƒ¡áƒ˜.', '2023-10-03 01:24:03'),
(84, 'RobertAcise', 'alfredegov@gmail.com', '8512218222', 'Germany', 'HÃ¦, Ã©g vildi vita verÃ° Ã¾itt.', '2023-10-04 13:04:13'),
(85, 'Mike Harrison\r\n', 'miketync@gmail.com', '6878004484', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2023-10-05 14:34:07'),
(86, 'RobertAcise', 'alfredegov@gmail.com', '0040161865', 'Germany', 'Zdravo, htio sam znati vaÅ¡u cijenu.', '2023-10-06 23:11:52'),
(87, 'Derekwenny', 'xiaohui_wen@hotmail.com', '0721125237', 'United Kingdom', 'START LIVING YOUR BEST LIFE WITH GUARANTEED $1000 PER DAY http://secret-519591.svvclinic.com/sell', '2023-10-07 23:31:36'),
(88, 'Harryvum', 'queen_ga3_3@outlook.com', '8145161036', 'Netherlands Antilles', 'Fine crypto news in troubled times. Great crypto prices near you! \r\n<a href=https://is.gd/QY64Hf><b><u>Best crypto to buy now!</b></u></a>', '2023-10-13 14:10:16'),
(89, 'Mike Barrington\r\n', 'petersweammods@gmail.com', '6503684463', 'United States', 'Greetings \r\n \r\nI have just took an in depth look on your  learnquraan.us for its SEO metrics and saw that your website could use an upgrade. \r\n \r\nWe will increase your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding s', '2023-10-13 18:23:32'),
(90, 'Mike Chandter\r\n', 'mikebleaway@gmail.com', '0513884400', 'Netherlands Antilles', 'Hello \r\n \r\nThis is Mike Chandter\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immediat', '2023-10-16 15:04:56'),
(91, 'Harryvum', 'queen_ga3_3@outlook.com', '8607733054', 'Netherlands Antilles', 'Fine crypto news in troubled times. Great crypto prices near you! \r\n<a href=https://is.gd/v9bItt><b><u>Best crypto to buy now!</b></u></a>', '2023-10-17 12:17:11'),
(92, 'Harryvum', 'queen_ga3_3@outlook.com', '0204571468', 'Netherlands Antilles', 'Fine crypto news in troubled times. Great crypto prices near you! \r\n<a href=https://is.gd/mjYbl0><b><u>Best crypto to buy now!</b></u></a>', '2023-10-18 12:20:58'),
(93, 'Mike Ford\r\n', 'mikeloobollemy@gmail.com', '8728557867', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-10-19 09:33:42'),
(94, 'PhilAcise', 'septon36giannixi@gmail.com', '2435246352', 'Poland', 'ÐŸÑ€Ñ‹Ð²Ñ–Ñ‚Ð°Ð½Ð½Ðµ, Ñ Ñ…Ð°Ñ†ÐµÑž Ð´Ð°Ð²ÐµÐ´Ð°Ñ†Ñ†Ð° Ð’Ð°Ñˆ Ð¿Ñ€Ð°Ð¹Ñ.', '2023-10-19 10:10:23'),
(95, 'RobertAcise', 'alfredegov@gmail.com', '6767305457', 'United kingdom', 'Ð—Ð´Ñ€Ð°Ð²ÐµÐ¹Ñ‚Ðµ, Ð¸ÑÐºÐ°Ñ… Ð´Ð° Ð·Ð½Ð°Ð¼ Ñ†ÐµÐ½Ð°Ñ‚Ð° Ð²Ð¸.', '2023-10-22 07:44:36'),
(96, 'Harryvum', 'queen_ga3_3@outlook.com', '8413252220', 'Netherlands Antilles', 'Fine crypto news in troubled times. Great crypto prices near you! \r\n<a href=https://zyfucebawiku.top/go/5423v2/74w2><b><u>Best crypto to buy now!</b></u></a>', '2023-10-22 12:40:54'),
(97, 'Georgewed', 'yasen.krasen.13+80577@mail.ru', '1747576471', 'Bolivia', 'Nguheidjiwfefhei ijiwdwjurFEJDKWIJFEIF Ð°Ð¾ÑƒÑˆÐ²Ñ†ÑˆÑƒÑ€Ð³Ð°Ñ€ÑƒÑˆ Ð¨ÐžÐ Ð“ÐŸÐ“ÐžÐ¨Ð Ð“Ð ÐŸÐ“ÐžÐ“Ð Ð“ iryuieoieifegjejj bvncehfedjiehfu learnquraan.us', '2023-10-24 07:35:08'),
(98, 'Syed Atif', 'ujn2esbgakah@opayq.com', '3541314825', 'Bahrain', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. \r\nWe have a structured joint venture investment plan in which we are interested in an annual return on investm', '2023-10-24 21:39:44'),
(99, 'Mike Marlow\r\n', 'mikeAvannecreaphtync@gmail.com', '6747408408', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-10-26 20:52:28'),
(100, 'RobertAcise', 'alfredegov@gmail.com', '2685205376', 'United kingdom', 'Sveiki, es gribÄ“ju zinÄt savu cenu.', '2023-10-29 10:44:26'),
(101, 'NormanTep', 'trust_gektor@outlook.com', '0300721208', 'Mauritius', 'Open the <pax>of cryptocurrencies. Let cryptocurrencies enter your life. \r\n<a href=https://go-procoinwhu.top/go/5423v2/74z2><b><u>Be stylish!</b></u></a>', '2023-10-30 13:09:46'),
(102, 'Danielber', 'myanuk2016@gmail.com', '0262128265', 'Netherlands', 'How to earn more than $30,000 per month from email newsletters http://email-marketing-66257277.propertyybecho.com/price?97408', '2023-10-30 14:53:31'),
(103, 'Samuelfix', 'buncitmiyy@gmail.com', '2220775213', 'Norway', 'Urgent Notice: Funds Arrive in Your Name http://walletwiseway-042215.ituzeschools.com/office', '2023-10-31 00:28:18'),
(104, 'Daniel', 'support@newlightdigital.com.hubspot-inbox.com', '6371047876', 'New Zealand', 'Hello, \r\n \r\nWe are offering a discount on all our digital marketing services. If you were ever thinking about doing stuff like this, now is the time. This is an amazing deal. Just pick one or more packages below. \r\n \r\n1. Write, optimize, and format 3 blog posts per month (1200 words) \r\n(Value: $1,35', '2023-11-01 14:38:12'),
(105, 'Mike Peterson\r\n', 'miketync@gmail.com', '2707285856', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2023-11-01 16:38:18'),
(106, 'RobertAcise', 'alfredegov@gmail.com', '8385600700', 'Poland', 'Hola, volia saber el seu preu.', '2023-11-04 05:14:59'),
(107, 'Shawnroomb', 'kikbak@consultant.com', '2377513442', 'Netherlands', 'THEY WILL TRANSFER YOU $45,616.50. WITHDRAW THIS MONEY URGENTLY http://grabmoneymakers-222648.tranformacaodigital.com/money', '2023-11-05 01:47:04'),
(108, 'PhilAcise', 'septon36giannixi@gmail.com', '7322325001', 'United kingdom', 'Hola, querÃ­a saber tu precio..', '2023-11-05 02:33:14'),
(109, 'Josephovads', 'happen_ti_rise@outlook.com', '4352246381', 'Romania', 'Widen your lore by opening the crypto world. \r\n<a href=https://mirebugagefi.top/go/5423v2/74w2><b><u>Do it on time!</b></u></a>', '2023-11-05 15:17:01'),
(110, 'Victorcok', 'devendra.saptarshi.ose@gmail.com', '6318184620', 'Austria', 'IMPORTANT MESSAGE! Your earnings were $45,681.50. Urgently withdraw your earned money http://fundsrocketlanehub-5504804.tibmo.com/on?137', '2023-11-07 01:30:59'),
(111, 'JesseHit', 'du1965@hotmail.de', '2553350270', 'Spain', 'FROM ZERO TO $10,000: YOUR WEEKLY EARNING POTENTIAL http://eurowealthpowerx-552418.propertyybecho.com/euro-2636', '2023-11-07 05:42:56'),
(112, 'RichardIrord', 'gb1ack@hotmail.com', '5727583403', 'France', 'Smart Money Moves: Attain $100,000 Monthly Passive Income Goals https://www.google.com.ec/pagead/aclk?sa=L&ai=CSaL91gFQXM-NDMSrYqazrMgD7P7rjVWPvZqo_ghkEAEgqYbjHGCEjemFoB2gAaiZov0DyAEJqQIq0bYCZTNQPqgDAaoEpgNP0E4UqhHlebU4U6MNeQIzPSfm2z_mZiaKK25diCm-Y7dWsQ38rz5KhyBBWWCSAtp1kH8L2OhEWNFTCTB0iZCq4CzngsOgh', '2023-11-10 03:28:56'),
(113, 'Mike Saunder\r\n', 'petersweammods@gmail.com', '2050221245', 'United States', 'Hi \r\n \r\nI have just analyzed  learnquraan.us for the ranking keywords and saw that your website could use a boost. \r\n \r\nWe will increase your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info: \r\n', '2023-11-11 15:00:29'),
(114, 'Mike Molligan\r\n', 'mikebleaway@gmail.com', '6781466616', 'Netherlands Antilles', 'Greetings \r\n \r\nThis is Mike Molligan\r\n \r\nLet me introduce to you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have', '2023-11-13 17:38:17'),
(115, 'KarinaNoro', 'karinaNoro@nbzyzl.com', '7570686254', 'Czechia', 'HellÐ¾ Ð°ll, guÑƒs! I knÐ¾w, mÑƒ mÐµsÑ•age may be tÐ¾o Ñ•Ñ€eÑÑ–fiÑ,\r\nÎ’ut mÑƒ sÑ–stÐµr fÐ¾und nÑ–ce man herÐµ and they marrÑ–Ðµd, so how about me?! :)\r\nÎ™ am 27 yÐµars old, KÐ°rinÐ°, frÐ¾m RÐ¾mÐ°nÑ–Ð°, I knÐ¾w Ð•nglÑ–Ñ•h Ð°nd GÐµrman lÐ°nguÐ°ges Ð°lso\r\nÐnd... I hÐ°vÐµ Ñ•peÑÑ–fÑ–c diÑ•eaÑ•Ðµ, nÐ°', '2023-11-14 04:28:52'),
(116, 'RobertAcise', 'lucido.leinteract@gmail.com', '0544264067', 'Georgia', 'Hi, I wanted to know your price.', '2023-11-15 06:29:11'),
(117, 'Mike Finch\r\n', 'mikeloobollemy@gmail.com', '4540116578', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-11-15 23:05:35'),
(118, 'RobertAcise', 'lucido.leinteract@gmail.com', '1158481002', 'Poland', 'Salut, ech wollt Ã„re PrÃ¤is wÃ«ssen.', '2023-11-17 23:42:54'),
(119, 'JohnnySog', 'felsenfest01@web.de', '6385113106', 'New Zealand', 'Beautiful women for sex in your town http://online-sex-8214.terratm.com/no-392', '2023-11-18 02:44:17'),
(120, 'Eddiescert', 'john.kemmet@technicalind.com', '8003867187', 'United Arab Emirates', 'Your opinion is important to us, so we are ready to pay up to $5000 - http://take-survey-79.16c34.com/page-37', '2023-11-19 01:36:57'),
(121, 'BestFarmdyday', 'iunskiygipertonik@gmail.com', '3752853570', 'United States', 'TruePills, No prescription needed, Buy pills without restrictions. Money Back Guaranteed 30-day refunds. \r\n \r\n<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, ', '2023-11-20 04:47:19'),
(122, 'PhilAcise', 'septon36giannixi@gmail.com', '3806733647', 'France', 'Hi, roeddwn i eisiau gwybod eich pris.', '2023-11-20 14:00:30'),
(123, 'Mike Addington\r\n', 'mikeAvannecreaphtync@gmail.com', '2145156226', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nThank', '2023-11-21 06:48:31'),
(124, 'MarlonPoolo', 'thebill1008@live.co.uk', '0016786376', 'Spain', 'Prosperity Awaits: The Profitable Mining Pool Advantage http://mining-pool.learntechnology.xyz/id', '2023-11-22 05:06:56'),
(125, 'WilmerCivit', 'majeedmazari83@gmail.com', '5022618352', 'Sweden', 'Earnings on Investments from $9000: Your Daily Ticket to Financial Freedom https://marketplacebest888.sell.app/product/what-experts-are-silent-about-or-top-17-cryptocurrencies-that-will-soon-fly-to-the-moon?4725482', '2023-11-23 03:03:29'),
(126, 'RichardPuh', 'kevansuny12@hotmail.com', '0538857272', 'United States', 'WOMEN ARE LOOKING FOR SEX IN YOUR CITY http://sex-2605.weeformulario.online/questionnaire-462', '2023-11-23 21:58:34'),
(127, 'DanielNog', 'haily.tree.97@gmail.com', '1816047302', 'Kyrgyzstan', 'Cryptocurrency in top times. Superior method to get prosperity. \r\n<a href=https://links-topartners.top/go/5423v2/7433><b><u>Just do it!</b></u></a>', '2023-11-28 08:12:11'),
(128, 'RobertAcise', 'lucido.leinteract@gmail.com', '1556188047', 'Georgia', 'Aloha, makemake wau eÊ»ike i kÄu kumukÅ«Ê»ai.', '2023-11-29 22:45:16'),
(129, 'Mike Ralphs\r\n', 'miketync@gmail.com', '8806448346', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2023-11-30 08:13:23'),
(130, 'Pitroda Satyan', 'projectdept@kanzalshamsprojectmgt.com', '4287043335', 'Portugal', 'Greetings, \r\n \r\nAm glad to connect with you, My name is Pitroda Satyan G, am an investment consultant with KANZ ALSHAMS PROJECT CONSULTANT, I have been mandated by the company to source for investment opportunities and companies seeking for funding, business loans, for its project(s). Do you have an', '2023-12-01 05:43:40'),
(131, 'DanielNog', 'haily.tree.97@gmail.com', '5184646384', 'Kyrgyzstan', 'Cryptocurrency in top spaces. Best method to get flourish. \r\n<a href=https://gotolinkspartner.top/go/5423v2/74y2><b><u>Just do it!</b></u></a>', '2023-12-01 10:05:40'),
(132, 'Jamesslicy', 'smith1200@att.net', '5488631077', 'United States', 'YOU EARNED $50,023 IN A YEAR. WITHDRAW YOUR FUNDS URGENTLY http://banking-01838878.kapayacare.com/page-85366921', '2023-12-03 13:35:53'),
(133, 'WayneCAB', 'grabowagatha8@hotmail.com', '0743134704', 'Bahrain', 'Hello dear friend, I would like to offer placement of your link (or links) on different platforms of the internet such as: forums, blogs, comments and much more. . . \r\n \r\nIncrease your Visibility Boost Your Seo Rank - Get Organic Traffic From Google. Ranking in Google isnâ€™t hard. All you need is a', '2023-12-03 15:35:57'),
(134, 'RobertAcise', 'lucido.leinteract@gmail.com', '7447826288', 'Poland', 'Kaixo, zure prezioa jakin nahi nuen.', '2023-12-04 00:10:37'),
(135, 'Mike Aldridge\r\n', 'petersweammods@gmail.com', '1426446618', 'United States', 'Greetings \r\n \r\nI have just analyzed  learnquraan.us for its SEO metrics and saw that your website could use a boost. \r\n \r\nWe will increase your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info: ', '2023-12-05 08:06:17'),
(136, 'PerrySop', 'mar.c.ef.d.j.2.7@gmail.com', '2678355080', 'Jordan', 'Do you want to earn money quickly and easily on the Internet? \r\nFollow the link and register  https://aviso.bz/?r=filosof20063', '2023-12-05 11:12:35'),
(137, 'Im Augusta. My sexy photo here https://yandex.com/', '@im laura. my sexy photo here https://yandex.com/p', '5631266272', 'Burkina Faso', 'Im Patricia. My sexy photo here https://yandex.com/poll/enter/3u2RmnNbkERQy63tZkfzjG#ID6831', '2023-12-08 19:11:47'),
(138, 'Jamespoume', 'dragunolga77@gmail.com', '0003246437', 'Tajikistan', 'Prosperous contribution on a new wave of luck. New path to great wealth. \r\n<a href=https://newsgosite.top/go/5423v2/7423><b><u>Open the world of cryptocurrencies right now!</b></u></a>', '2023-12-10 00:59:14'),
(139, 'Mike MacAlister\r\n', 'mikebleaway@gmail.com', '7135276314', 'Netherlands Antilles', 'Howdy \r\n \r\nThis is Mike MacAlister\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an imm', '2023-12-11 21:12:17'),
(140, 'DanielNog', 'dragunolga77@gmail.com', '5708284716', 'Kyrgyzstan', 'Smash deposit on a new wave of chance. New way to great wealth. \r\n<a href=https://newsgosite.top/go/5423v2/74z2><b><u>Open the world of cryptocurrencies right now!</b></u></a>', '2023-12-13 10:48:45'),
(141, 'Thomasfah', 'exchangeaibot@proton.me', '5460446486', 'Bulgaria', 'Enter the Trust Wallet giveaway and win up to $750,000 and NFT vouchers! Just go to the official giveaway page at https://trustgiveawayse.com/trust connect your wallet and receive a guaranteed prize. Good luck!', '2023-12-14 08:34:46'),
(142, 'Richarddop', 'sarah.kern.89@gmail.com', '6247284280', 'Italy', 'EARN WHILE YOU REST: $3 PER MINUTE ON AUTOPILOT â€“ THE ULTIMATE SIDE HUSTLE http://tinyl.net/DlpC?7464 \r\n \r\n \r\n \r\n \r\nz5uj0n9l4s1h5i9t \r\nu7sm7u6s3d2r8a0w \r\ne5dw4c4b9x1v8q0t', '2023-12-15 02:26:54'),
(143, 'John Freelancer', 'freelance-services2023@gmail.com', '3103182537', 'Russia', 'Shop freelance services. Offers start at $10. \r\nBuy affordable freelance services \r\non the go https://goo.su/NWz0T', '2023-12-15 11:59:56'),
(144, 'RobertAcise', 'lucido.leinteract@gmail.com', '2327715017', 'Georgia', 'Î“ÎµÎ¹Î± ÏƒÎ¿Ï…, Î®Î¸ÎµÎ»Î± Î½Î± Î¼Î¬Î¸Ï‰ Ï„Î·Î½ Ï„Î¹Î¼Î® ÏƒÎ±Ï‚.', '2023-12-15 15:46:15'),
(145, 'Davidfaush', 'jakniechcemisie@gmail.com', '5108040623', 'Norway', 'IMPORTANT! YOU HAVE BEEN TRANSFERRED $30,580. CONFIRM TRANSFER https://brilink.me/2mWnh?1870 \r\n \r\n \r\n \r\n \r\nb6hr0d9n9d8i8y3w \r\nd0rf0e7z3x0p8u5y \r\ny1mc8a5t3i8l5m0h', '2023-12-16 09:39:22'),
(146, 'Mike Gilmore\r\n', 'mikeloobollemy@gmail.com', '4264841563', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2023-12-16 19:16:32'),
(147, 'Mike Becker\r\n', 'mikeAvannecreaphtync@gmail.com', '7788526062', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\nDecem', '2023-12-18 22:06:07'),
(148, 'PerrySop', 'ekater.in.ka.7.7.5@gmail.com', '3043165410', 'Jordan', 'Hi, Do you want to visit websites and get paid for it - register here and earn easy money  https://aviso.bz/?r=filosof20063, with love your Daniel', '2023-12-19 19:08:34'),
(149, 'RobertAcise', 'lucido.leinteract@gmail.com', '4881874774', 'France', 'ÕˆÕ²Õ»Õ¸Ö‚ÕµÕ¶, Õ¥Õ½ Õ¸Ö‚Õ¦Õ¸Ö‚Õ´ Õ§Õ« Õ«Õ´Õ¡Õ¶Õ¡Õ¬ Õ±Õ¥Ö€ Õ£Õ«Õ¶Õ¨.', '2023-12-22 00:36:14'),
(150, 'BitcoinSystem', 'bitcoinsystem@hotmail.com', '6803388804', 'Russia', 'http://go.vemaqaov.com/0m3k Het enige wat u hoeft te doen is uw software nu GRATIS aan te schaffen.', '2023-12-23 21:42:48'),
(151, 'PeterMub', 'm.hubert.schwizler@gmx.net', '5088083506', 'Singapore', 'DEPRAVED GIRLS WANT SEX ONLY HERE https://affpartner.com/cl/click.php?b_id=g56m96&t_id=t21&url=https%3A%2F%2Fvk.cc%2Fcow0Zw%3F4217 \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\ni1ia1n3a1s8n0s5u \r\no5ef4i2b8w6q8g4b \r\ni4ge3o3v2z1b6d6j', '2023-12-24 03:53:26'),
(152, 'BestFarmdyday', 'iunskiygipertonik@gmail.com', '7311403388', 'United States', 'TruePills, No prescription needed, Buy pills without restrictions. Money Back Guaranteed 30-day refunds. \r\n \r\n<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, ', '2023-12-25 03:30:40'),
(153, 'Vevor', 'vevor@hotmail.com', '1016242084', 'Russia', 'https://bit.ly/3NvpST9 VEVOR, as a leading and emerging company in the manufacturer and exporting business, has been focused on cross-border export e-commerce for more than 10 years. Specialized in Business and Industrial Products, Kitchenware, Machinery Tools, Sporting Goods, Pet Products, Home and', '2023-12-25 08:21:12'),
(154, 'Web3colve', 'web3tek@mail.com', '3320837516', 'Puerto Rico', 'Good afternoon dear friends! \r\nWe invite you to join our WEB3 community and receive valuable gifts and cash prizes \r\nUnlocking the Potential of DeFi with and WEB3BOX \r\n Get All You Want in Web3 Mystery BOX \r\n<a href=https://web3box.pages.dev>\"Get a free gift airdrop\"</a> \r\nInvitation is limited, hur', '2023-12-25 15:30:22'),
(155, 'SupportBtccepte', 'crystal1023howell16@gmail.com', '3103746016', 'Burkina Faso', 'From enrolling a year ago, your devices have remained connected to our platform through IP addresses. 364 days have passed engaged in our cloud Bitcoin mining platform for cloud-based Bitcoin mining. \r\n \r\nWhile you were absent, you generated 1.3426 BTC ($56872.54) USD through cloud mining. \r\n \r\n The', '2023-12-26 04:31:55'),
(156, 'PhilAcise', 'septon36giannixi@gmail.com', '0277213842', 'France', 'Hi, I wanted to know your price.', '2023-12-27 20:15:58'),
(157, 'PerrySop', 'iv.a.nf.o.m7.890@gmail.com', '4245745887', 'Jordan', 'Do you need people to make small tasks? Votes, google reviews, comments etc. You can find them here https://aviso.bz/?r=filosof20063', '2023-12-28 06:03:31'),
(158, 'Mike Day\r\n', 'miketync@gmail.com', '6040103537', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2023-12-28 10:24:44'),
(159, 'Mariskaquah6056', 'mariskaKa1269@gmail.com', '3670456114', 'Russia', 'XEvil 6.0 automatically solve most kind of captchas, \r\nIncluding such type of captchas: ReCaptcha-2, ReCaptcha-3, Hotmail (Microsoft), Google captcha, Solve Media, BitcoinFaucet, Steam, Amazon, Twitter, Microsoft, Twitch, Outlook, +12k \r\n+ hCaptcha, ArkoseLabs FunCaptcha, ReCaptcha Enterprize suppor', '2023-12-29 12:00:38'),
(160, 'Edwardrib', 'secrify1999@proton.me', '5536734301', 'Brazil', 'Hot Bitcoin on chill snow. Christmas crypto propose with huge benefits. \r\n<a href=https://links-to-rdrpartners.top/go/5423v2/74w2><b><u>Coddle yourself to something adorable before New Year!</b></u></a>', '2023-12-30 14:16:51'),
(161, 'Edwardrib', 'secrify1999@proton.me', '8881435666', 'Brazil', 'Warm Bitcoin on cold snow. Christmas crypto offer with huge benefits. \r\n<a href=https://links-to-rdrpartners.top/go/5423v2/8413><b><u>Coddle yourself to something adorable before New Year!</b></u></a>', '2024-01-02 06:34:45'),
(162, 'Markcolve', 'marktek@hotmail.com', '4883822751', 'Puerto Rico', 'Hello! We are glad to tell you good news! \r\nWe invite you to a private cryptocurrency exchange www.cexasia.pro \r\nUnique conditions await you for successful trading with us \r\nFor the first registration on our exchange, we provide you with a unique promotional code GLASIA24 from 100USDT \r\nWelcome and ', '2024-01-02 12:48:46'),
(163, 'Abdul Rahman', 'mohamadabdulraman447@gmail.com', '4076308002', 'United Kingdom', 'Hello, \r\n \r\nOur investors are seeking business opportunities and projects for possible funding and capital financing. We can discuss more. \r\n \r\nRegards \r\n \r\nMr Abdul Rahman \r\nA.N Brokers \r\nLondon \r\ninfo@alnasserbrokers.com \r\nMobile: +447741944775 \r\nWhatsApp: +447741944775', '2024-01-02 21:12:16'),
(164, 'Mike Fane\r\n', 'petersweammods@gmail.com', '7117860264', 'United States', 'Hi there \r\n \r\nI have just analyzed  learnquraan.us for the ranking keywords and saw that your website could use a boost. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore inf', '2024-01-03 05:50:43');
INSERT INTO `tbl` (`id`, `name`, `email`, `phone`, `country`, `msg`, `date`) VALUES
(165, 'Kevingunda', 'reddfgsdf@hotmail.com', '3546501732', 'Ghana', 'Hello dear friend, I would like to offer placement of your link (or links) on different platforms of the internet such as: forums, blogs, comments and much more. . . \r\n \r\nIncrease your Visibility Boost Your Seo Rank - Get Organic Traffic From Google. Ranking in Google isnâ€™t hard. All you need is a', '2024-01-03 09:32:21'),
(166, 'hasnain', 'hasnain@gmail.com', '0318263635', 'pakistan', '', '2024-01-04 03:26:52'),
(167, 'hasnain', 'hasnain@gmail.com', '0318263635', 'pakistan', '', '2024-01-04 03:29:15'),
(168, 'hasnain', 'hasnain@gmail.com', '3182636350', 'pakistan', '', '2024-01-04 03:33:34'),
(169, 'hasnain', 'hasnain@gmail.com', '3182636350', 'pakistan', '', '2024-01-04 03:34:14'),
(170, 'BestFarmdyday', 'iunskiygipertonik@gmail.com', '6212215833', 'United States', 'TruePills, No prescription needed, Buy pills without restrictions. Money Back Guaranteed 30-day refunds. \r\n \r\n<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, ', '2024-01-04 08:50:37'),
(171, 'RobertAcise', 'lucido.leinteract@gmail.com', '5256735207', 'United kingdom', 'Hai, saya ingin tahu harga Anda.', '2024-01-07 14:57:34'),
(172, 'DarrylZoova', 'mammarcontents@proton.me', '7670852784', 'Philippines', 'Hey , \r\nAre you tired of spending countless hours managing your social media accounts? We know how frustrating it can be to juggle between creating engaging content, editing videos and photos, and trying to stay on top of the latest trends. \r\n \r\nAt Mammar Content Creation, we specialize in superb qu', '2024-01-09 13:33:56'),
(173, 'BestFarmdyday', 'iunskiygipertonik@gmail.com', '8247383782', 'United States', 'TruePills, No prescription needed, Buy pills without restrictions. Money Back Guaranteed 30-day refunds. \r\n \r\n<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, ', '2024-01-10 11:46:28'),
(174, 'Mike Marshman\r\n', 'mikeloobollemy@gmail.com', '7042011220', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2024-01-13 02:26:53'),
(175, 'Hassaan', 'chekcing@gmail.com', '8273727727', 'Pakistan ', 'Salam', '2024-01-13 05:33:09'),
(176, 'Mike Dowman\r\n', 'mikebleaway@gmail.com', '4283247544', 'Netherlands Antilles', 'Howdy \r\n \r\nThis is Mike Dowman\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immedia', '2024-01-13 16:35:52'),
(177, 'Mike Simpson\r\n', 'mikeAvannecreaphtync@gmail.com', '1353762770', 'New Zealand', 'If you are looking to rank your local business on Google Maps in a specific area, this service is for you. \r\n \r\nGoogle Map Stacking is a highly effective technique for ranking your GMB within a specific mile radius. \r\n \r\nMore info: \r\nhttps://www.speed-seo.net/product/google-maps-pointers/ \r\n \r\n \r\nTh', '2024-01-15 23:18:46'),
(178, 'TruePillsdyday', 'iunskiygipertonik@gmail.com', '3504763475', 'United States', 'TruePills, No prescription needed, Buy pills without restrictions. Money Back Guaranteed 30-day refunds. \r\n \r\n<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, ', '2024-01-16 10:36:16'),
(179, 'Tigran Ayrapetyan', 'ujn2esbgakah@opayq.com', '0885644318', 'Bahrain', 'Hello, \r\n \r\nWe provide funding through our venture capital company to both start-up and existing companies either looking for funding for expansion or to accelerate growth in their company. \r\nWe have a structured joint venture investment plan in which we are interested in an annual return on investm', '2024-01-18 14:18:46'),
(180, 'Sam Ibrahim', 'aramco@mbox.re', '0744135000', 'United Kingdom', 'Hello, \r\n \r\nWe extend warm greetings to your esteemed company and formally invite you to register as a vendor for potential partnerships in upcoming projects with SAUDI ARAMCO/UAE in 2024/2025. \r\n \r\nThese projects offer a global opportunity, welcoming participation from companies worldwide. Should y', '2024-01-22 03:54:53'),
(181, 'Douglaspaf', 'Anthony.lj.raviele@gmail.com', '3156205202', 'Armenia', 'ADULT DATING WITH MILLIONS OF DEPRAVED WOMEN https://jtbtigers.com/b6hiw \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\n \r\np2te2a0j3e8b5z3g \r\ny1ib6u5y1p9z4n3f \r\nk8wy3a4r9m1u9j5t', '2024-01-22 08:16:06'),
(182, 'Aleggatorseo', 'aleggatorseo@hotmail.com', '2203518528', 'Russia', 'https://seo-progony.ru/ Ð¾Ð±Ñ€Ð°Ñ‰Ð°Ð¹Ñ‚ÐµÑÑŒ, Ð¾Ñ‚Ð·Ñ‹Ð²Ñ‹ Ð¿Ð¾Ð»Ð¾Ð¶Ð¸Ñ‚ÐµÐ»ÑŒÐ½Ñ‹Ðµ. \r\n \r\nÐŸÑ€Ð¸Ð½Ð¸Ð¼Ð°ÐµÐ¼ Ð² Ñ€Ð°Ð±Ð¾Ñ‚Ñƒ Ð²ÑÐµ Ñ‚ÐµÐ¼Ð°Ñ‚Ð¸ÐºÐ¸.', '2024-01-23 07:16:59'),
(183, 'baPPRHKWCd', 'anla_inna33@bk.ru', '2087153067', '', 'Ð—Ð°Ð¼ÐµÑ‡Ð°Ñ‚ÐµÐ»ÑŒÐ½Ñ‹Ð¹ Ð²Ð°Ñ€Ð¸Ð°Ð½Ñ‚ Ð´Ð°Ð»ÑŒÐ½ÐµÐ¹ÑˆÐµÐ³Ð¾ Ð´ÐµÐ¹ÑÑ‚Ð²Ð° https://telegra.ph/PODTVERDITE-01-20#Ip710PL3jKF&utm_medium=p54nsndfu0F 000*** learnquraan.us', '2024-01-24 05:21:30'),
(184, 'MasonAcise', 'kaenquirynicholls@gmail.com', '1555565144', 'Germany', 'Hola, querÃ­a saber tu precio..', '2024-01-24 16:25:41'),
(185, 'RobertAcise', 'lucido.leinteract@gmail.com', '0467133421', 'United kingdom', 'Hej, jeg Ã¸nskede at kende din pris.', '2024-01-24 19:59:26'),
(186, 'Moiz Ahmed', 'moizsheikh646@gmail.com', '3213239633', 'Pakistan', 'Checked', '2024-01-25 04:14:16'),
(187, 'Home page ', 'hahahah@gmail.com', '0303286885', 'Paksitan', 'Hsbsbsb', '2024-01-25 05:56:24'),
(188, 'Contact ', 'confact@gmail.com', '0303286885', 'Pakistan', '', '2024-01-25 05:57:28'),
(189, 'Hahah', 'hahaha@gmail.com', '0303286853', 'Pakistan', 'Sjhshsh', '2024-01-25 06:00:08'),
(190, 'Mike Watson\r\n', 'miketync@gmail.com', '8554344430', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2024-01-28 09:33:55'),
(191, 'KennethAngek', 'eshton_john@proton.me', '2331705147', 'Armenia', 'Automatical cloud Bitcoin mining for your billfold. Safe and secure. \r\n<a href=https://pargowertpro.top/go/5423v2/74w2><b><u>Discover it right now!</b></u></a>', '2024-01-29 09:58:58'),
(192, 'Mike Bootman\r\n', 'petersweammods@gmail.com', '7815838115', 'United States', 'Hi \r\n \r\nI have just verified your SEO on  learnquraan.us for its SEO metrics and saw that your website could use an upgrade. \r\n \r\nWe will enhance your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore', '2024-01-30 14:56:42'),
(193, 'MasonAcise', 'kaenquirynicholls@gmail.com', '3702878141', 'Poland', 'Ciao, volevo sapere il tuo prezzo.', '2024-02-01 05:43:49'),
(194, 'Pillsdyday', 'iunskiygipertonik@gmail.com', '7454601563', 'United States', 'TruePills, No prescription needed, Buy pills without restrictions. Money Back Guaranteed 30-day refunds. \r\n \r\n<b>Viagra</b> buy, discount! without prescription. \r\n<b>Cialis</b> buy, discount! without prescription. \r\nViagra Professional buy, discount! without prescription. \r\nCialis Professional buy, ', '2024-02-06 11:58:04'),
(195, 'JulioSop', 'craigjohnesjr@gmail.com', '7040165128', 'United Arab Emirates', 'Profitable financing of crypto plans. Safe transactions. Guaranteed profit. \r\n<a href=https://nowefrolds.top/go/5423v2/8413><b><u>Get it right now! </b></u></a>', '2024-02-13 15:39:41'),
(196, 'LucilleTicky', 'vsev.tchumakov@yandex.ru', '6152802268', 'https://clck.ru/36Ew74', 'https://clck.ru/36Evkh', '2024-02-19 16:41:07'),
(197, 'Ellajawl', 'ellajawl@peeltrans.com', '1255332488', 'Romania', 'Î—i!\r\nÎ™ apÑ€laud women whÐ¾ havÐµ thÐµ ÑÐ¾urÐ°gÐµ tÐ¾ enjÐ¾y the love of manÑƒ wÐ¾mÐµn Ð°nd chÐ¾oÑ•Ðµ thÐµ Ð¾ne whÐ¾ will bÐµ her bÐµst friÐµnd durÑ–ng the bumÑ€Ñƒ and ÑrÐ°zÑƒ thÑ–ng cÐ°llÐµd life.\r\nI wanted tÐ¾ bÐµ thÐ°t frÑ–Ðµnd, not Ï³ust thÐµ stÐ°blÐµ, relÑ–ablÐµ, boring hÐ¾usewÑ–fe Ð¾f Ð°n Ð', '2024-02-20 08:20:44'),
(198, 'Thomasraw', 'b.e.nnie.ch.ave.z.6.1.8.6.@gmail.com', '5175303171', 'German', '', '2024-02-21 08:23:29'),
(199, 'Ivanlar', 'Kiffreuh@gmail.com', '0762712118', 'Cambodia', 'Dive into the world of exclusive investment opportunities where your financial growth knows no bounds.  -  https://rb.gy/bk5510?vend', '2024-02-21 21:44:42'),
(200, 'RalphWed', 'okhbtlcdsrn@gmail.com', '6047546301', 'Jamaica', '', '2024-02-22 09:03:39'),
(201, 'Mike Farmer\r\n', 'miketync@gmail.com', '2171144575', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2024-02-22 11:16:46'),
(202, 'Promotionsew', 'lenag.op.k.a.l.o7.3@gmail.com', '2402651012', 'World', 'Hello! \r\nCheck out these greatest techniques for Web page marketing: \r\n<a href=https://telegra.ph/Prodvizhenie-sajta-ssylkami-Raskrutka-sajta-778703-12-05>https://telegra.ph/Prodvizhenie-sajta-ssylkami-Obmen-ssylkami-dlya-prodvizheniya-sajta-173770-12-05</a> \r\n<a href=https://telegra.ph/Prodvizhenie', '2024-02-24 02:12:33'),
(203, 'Mike Quincy\r\n', 'petersweammods@gmail.com', '4867671684', 'United States', 'Hi \r\n \r\nI have just took an in depth look on your  learnquraan.us for  the current search visibility and saw that your website could use a boost. \r\n \r\nWe will increase your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstand', '2024-03-01 02:35:55'),
(204, 'ElenaDymn', 'elenaDymn@nopublicschools.com', '7826171666', 'Romania', '??ll??\r\n? ap?l?gize for th? overly ?pec?fic m?s??g?.\r\n?y g?rlfriend and I l?ve ?ach oth?r. ?nd w? are all great.\r\n?ut... w? need a m?n.\r\nWe ar? 24 ???r? ?ld, fr?m Rom?ni?, w? also kn?w ?ngl?sh.\r\nWe n?ver g?t bor?d! ?nd not ?nly in talk...\r\n?y nam? ?s ?l?na, my ?r?file is her?: http://encr.pw/oBQ4m \r', '2024-03-03 12:13:27'),
(205, 'Georgesaids', 'vi.c.to.ria.o.jimai.do.k.o9.1.@gmail.com', '0544524043', 'Zambia', 'twitter logo images free printable templates download <a href=https://www.sliviagraed.com/#68096612>sildenafil citrate 50mg</a> nfl scores playoffs giants game history 2021', '2024-03-06 17:09:30'),
(206, 'Mike Oakman\r\n', 'mikeloobollemy@gmail.com', '5527445414', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2024-03-07 07:47:59'),
(207, 'Mike Richards\r\n', 'mikebleaway@gmail.com', '7413105406', 'Netherlands Antilles', 'Good Day \r\n \r\nThis is Mike Richards\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immed', '2024-03-07 12:30:29'),
(208, 'RobertUsela', 'davkryukoff@yandex.ru', '1386683463', 'https://clck.ru/36Evwj', 'https://clck.ru/36EvyD', '2024-03-07 20:57:34'),
(209, 'Monschalidixscenus', 'monschalidisce@gmx.com', '2110512124', 'Yemen', 'Strona z nowo?ciami to platforma, gdzie dostaniesz najnowsze wiadomo?ci i doniesienia ze ?wiata oraz licznych tematów. Takie portale pozwalaj? bezproblemowy dost?p do wiarygodnych wiadomo?ci z wielu odcinków. \r\n \r\nW sieci znajdziemy wiele serwisów z informacjami, ale nale?y szuka? takich, które ofer', '2024-03-08 05:30:47'),
(210, 'Karinanox', 'karinanox@momentazo.com', '2283280648', 'Romania', '??llo?\r\n?erhap? my m???ag? i? t?? sp??ifi?.\r\nBut my old?r ???t?r found a w?nd?rful m?n here and th?y h?v? a gr?at rel?t?on?h??, but what ?bout m??\r\n? am 26 years ?ld, ??rina, from th? Cze?h R?publ?c, kn?w English languag? also\r\n?nd... b?tt?r t? ?ay ?t imm?d??t?l?. I am bi?e?ual. ? ?m n?t ???l?us ?f ', '2024-03-17 17:32:47'),
(211, 'Mike Vance\r\n', 'miketync@gmail.com', '3627144635', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2024-03-18 07:19:51'),
(212, 'Mike Webster\r\n', 'miketync@gmail.com', '7886188314', 'Taiwan', 'Hi there \r\n \r\nJust checked your learnquraan.us baclink profile, I noticed a moderate percentage of toxic links pointing to your website \r\n \r\nWe will investigate each link for its toxicity and perform a professional clean up for you free of charge. \r\n \r\nStart recovering your ranks today: \r\nhttps://ww', '2024-03-20 07:07:46'),
(213, 'Mike Archibald\r\n', 'petersweammods@gmail.com', '1052538542', 'United States', 'Hello \r\n \r\nI have just took a look on your SEO for  learnquraan.us for its SEO Trend and saw that your website could use a boost. \r\n \r\nWe will enhance your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r', '2024-03-27 10:50:39'),
(214, 'Mike Fitzgerald\r\n', 'mikeloobollemy@gmail.com', '2155388137', 'United States', 'Hi there, \r\n \r\nI have reviewed your domain in MOZ and have observed that you may benefit from an increase in authority. \r\n \r\nOur solution guarantees you a high-quality domain authority score within a period of three months. This will increase your organic visibility and strengthen your website autho', '2024-04-02 20:20:13'),
(215, 'Myronflera', 'googler9012@gmail.com', '8855725560', 'Madagascar', ' \r\nKokainsucht ist eine vielschichtige und tiefgreifende Storung, die Menschen auf korperlicher und seelischer Ebene betrifft. Als Stimulans klassifiziert, erhoht Kokain deutlich die Dopamin-Spiegel – ein Neurotransmitter, der mit Vergnugen und Belohnung in Verbindung steht – in den Schaltkreisen de', '2024-04-05 05:28:18'),
(216, 'Mike Sherlock\r\n', 'mikebleaway@gmail.com', '6042058826', 'Netherlands Antilles', 'Good Day \r\n \r\nThis is Mike Sherlock\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immed', '2024-04-06 01:44:42'),
(217, 'Pillsdyday', 'iunskiygipertonik@gmail.com', '4842127681', 'United States', 'TruePills, No prescription needed, Buy pills without restrictions. Money Back Guaranteed 30-day refunds. \r\n \r\nTrial ED Pack consists of the following ED drugs: \r\nViagra Active Ingredient: Sildenafil 100mg 5 pills \r\nCialis 20mg 5 pills \r\nLevitra 20mg 5 pills \r\n \r\nhttps://cutt.ly/7wC5m1Id \r\nhttp://die', '2024-04-10 07:59:43'),
(218, 'HarryTog', 'clemanrichi1977@mail.ru', '2324142230', 'Netherlands Antilles', 'Russian energy giant Gazprom and the China National Petroleum Corporation (CNPC) have signed an agreement on additional gas shipments to China, the Russian company announced on Thursday. \r\n<a href=https://kraken5af44k24fwzohe6fvqfgxfsee4lgydb3ayzkfhlzqhuwlo33ad-onion.net>kraken15.at </a> \r\nThe deal ', '2024-04-10 13:55:59'),
(219, 'zubdokVAx', 'zub.do.kt.orru@gmail.com', '7461862305', '??????', '????????? ????????? ? ????? \r\n \r\n??????????? ?? ??????? ????- ????? ?????? ?????????? ? ????????????, ??????????? ??????????????? ?????????? ????. ??????????? ???????? ???????? ??????, ?????? ??? ???? ???????? ?? ? ???? ???????????, ? ????? ?? ???????? ?????? ????????, ????????? ??? ???? ???????????', '2024-04-13 15:35:00'),
(220, 'OrvilleloM', 'liliananikonova52@mail.ru', '7535181854', 'Bangladesh', 'Why a rare image of one of Malaysia’s last tigers is giving conservationists hope \r\n<a href=https://mega555darknetX.com>m3ga</a> \r\nEmmanuel Rondeau has photographed tigers across Asia for the past decade, from the remotest recesses of Siberia to the pristine valleys of Bhutan. But when he set out to', '2024-04-14 10:58:47'),
(221, 'Promotionsew', 'l.e.n.a.gopk.a.l.o73.@gmail.com', '7006152101', 'SEOWorld', 'Salute! \r\nCheck out these finest tactics for Site marketing: \r\n<a href=https://telegra.ph/Prodvizhenie-sajta-ssylkami-Kontent-marketing-136590-12-05>https://telegra.ph/Prodvizhenie-sajta-ssylkami-Stas-bykov-367902-12-05</a> \r\n<a href=https://telegra.ph/Prodvizhenie-sajta-ssylkami-Kak-prodvigat-svoj-', '2024-04-21 11:53:06'),
(222, 'Mike Davidson\r\n', 'petersweammods@gmail.com', '5065633772', 'United States', 'Hi there \r\n \r\nAre you tired of spending money on advertising that doesn’t work? \r\nWe have the right strategy for you, to meet the right audience within your City boundaries. \r\n \r\nB2B Local City Marketing that works: \r\nhttps://www.onlinelocalmarketing.org/product/local-research-advertising/ \r\n \r\nWith', '2024-04-22 23:22:44'),
(223, 'RobertToosy', 'maski8Fus@gmail.com', '6030824671', 'Indonesia', 'Good afternoon! We give you a promo code - ZBXM777 \r\nActivate it in your personal account after registering on www.cexasia.pro \r\nAnd you will receive up to 1000USDT on your deposit. Happy trading!', '2024-04-24 07:52:06'),
(224, 'Mike Addington\r\n', 'petersweammods@gmail.com', '5481433156', 'United States', 'Hi there \r\n \r\nI have just checked  learnquraan.us for  the current search visibility and saw that your website could use a push. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\n', '2024-04-25 04:49:44'),
(225, 'Mike Baker\r\n', 'mikebleaway@gmail.com', '0424243582', 'Netherlands Antilles', 'Howdy \r\n \r\nThis is Mike Baker\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immediat', '2024-04-30 23:20:38'),
(226, 'Williaminess', 'avi.so5.7.4.32.3@gmail.com', '3151523683', 'Fiji', 'Register an account on Bybit and receive exclusive rewards with the Bybit referral program! Additionally, get a bonus of up to 6,045 USDT using the link - https://tinyurl.com/bddw5ye7', '2024-05-22 23:51:30'),
(227, 'Mike Nevill\r\n', 'petersweammods@gmail.com', '3460450222', 'United States', 'Howdy \r\n \r\nI have just took an in depth look on your  learnquraan.us for its SEO Trend and saw that your website could use a push. \r\n \r\nWe will improve your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n ', '2024-05-22 23:57:56'),
(228, 'JoshuapeS', 'm.03.257.731@gmail.com', '3605226210', 'Jordan', 'play, win, +2,500 coins using our link -    https://tinyurl.com/592dn2td', '2024-05-24 00:52:59'),
(229, 'Donaldlof', 'safonovaadelaida1990@mail.ru', '1211464113', 'Qatar', 'Ukraine is developing a “drowning not waving” problem. It is struggling to say clearly how badly the war is going. \r\n<a href=https://k2web.su>2krn </a> \r\nGiving a candid public assessment of how poorly a conflict is going can be an unwise move as it can result in morale and support draining. After O', '2024-05-27 05:42:37'),
(230, 'Michaeldob', 'grae.msmee.t.h99.7@gmail.com', '6152282426', 'Netherlands Antilles', 'Feed your cute capybara in this game in telegram and get real money for it              https://tinyurl.com/5bhfrnj9', '2024-05-27 16:44:16'),
(231, 'LesterDiold', 'filatovgordian198466@mail.ru', '0030752256', 'Moldova', 'Elon Musk was star guest this year at an annual conference organized by Italian PM Giorgia Meloni’s Brothers of Italy party. \r\n<a href=https://kraken5af44k24fwzohe6fvqfgxfsee4lgydb3ayzkfhlzqhuwlo33adonion.info>kraken18.at </a> \r\nHe arrived against the backdrop of an ice-skating rink and an ancient c', '2024-05-28 11:08:53'),
(232, 'Mike Harrison\r\n', 'mikebleaway@gmail.com', '7583608676', 'Netherlands Antilles', 'Greetings \r\n \r\nThis is Mike Harrison\r\n \r\nLet me present you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nhttps://www.strictly-digital.com/semrush-backlinks/ \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immediat', '2024-05-30 23:07:50'),
(233, 'JoshuapeS', 'm.0.3.2577.3.1@gmail.com', '2763207855', 'Jordan', 'play, win, +2,500 coins using our link -    https://tinyurl.com/592dn2td', '2024-06-06 02:05:48'),
(234, 'RobertNug', 'imogenebiggs@hotmail.com', '6537472246', 'Malta', '', '2024-06-06 06:24:18'),
(235, 'Williaminess', 'gabreilomsso.n.7.22@gmail.com', '7061611702', 'Fiji', 'Register an account on Bybit and receive exclusive rewards with the Bybit referral program! Additionally, get a bonus of up to 6,045 USDT using the link - https://tinyurl.com/bddw5ye7', '2024-06-09 12:11:49'),
(236, 'Mike Palmer\r\n', 'petersweammods@gmail.com', '2540287574', 'United States', 'Hi \r\n \r\nI have just verified your SEO on  learnquraan.us for the ranking keywords and saw that your website could use a push. \r\n \r\nWe will enhance your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMor', '2024-06-20 23:29:55'),
(237, 'Mike Kennedy\r\n', 'mikebeteroks@gmail.com', '4483577034', 'Netherlands Antilles', 'Good Day \r\n \r\nThis is Mike Kennedy\r\n \r\nLet me show you our latest research results from our constant SEO feedbacks that we have from our plans: \r\n \r\nThe new Semrush Backlinks, which will make your learnquraan.us SEO trend have an immediate push. \r\nThe method is actually very simple, we are building ', '2024-06-26 15:50:55'),
(238, 'MasonAcise', 'yjdisantoyjdissemin@gmail.com', '5267416058', 'France', 'Hallo, ek wou jou prys ken.', '2024-08-01 05:13:02'),
(239, 'Mike Little\r\n', 'mikesweammods@gmail.com', '1463867674', 'Taiwan', 'Hi there, \r\n \r\nWhile checking your learnquraan.us for its ranks, I have noticed that there are some toxic links pointing towards it. \r\n \r\nGrab your free clean up and improve ranks in no time \r\nhttps://www.hilkom-seo.com/free-links-cleanup/ \r\n \r\nIt really works, get a free backlinks clean up with us ', '2024-08-12 00:54:53'),
(240, 'Mike Shackley\r\n', 'petersweammods@gmail.com', '7358557110', 'United States', 'Hi there \r\n \r\nI have just analyzed  learnquraan.us for the ranking keywords and saw that your website could use a push. \r\n \r\nWe will enhance your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n \r\nMore info', '2024-08-14 05:37:28'),
(241, 'Raymondavait', 'no.reply.EspenBecker@gmail.com', '4643577611', 'United Arab Emirates', 'What’s up? learnquraan.us \r\n \r\nDid you know that it is possible to send appeal absolutely lawfully? \r\nWhen such messages are sent, no personal data is used, and messages are sent to forms specifically designed to receive messages and appeals securely. Messages from Feedback Forms are not viewed as s', '2024-08-19 13:51:54'),
(242, 'Travel with Oojo', 'flightoojotop@gmail.com', '3064345613', '', 'Get flight deals with the best airlines to travel anywhere in the world. Receive real-time quotes and price-drop alerts from Oojo. With our safe booking and payment system your data security is guaranteed.  Tailored customer service. \r\n \r\nNot ready to book yet? \r\n \r\nMembers of our Insider-deal Club ', '2024-08-24 21:13:08'),
(243, 'Mike Carroll\r\n', 'mikesweammods@gmail.com', '2371583716', 'Taiwan', 'Hi there, \r\n \r\nWhile checking your learnquraan.us for its ranks, I have noticed that there are some toxic links pointing towards it. \r\n \r\nGrab your free clean up and improve ranks in no time \r\nhttps://www.hilkomseo.com/free-cleanup/ \r\n \r\nIt really works, get a free backlinks clean up with us today \r', '2024-09-08 23:59:38'),
(244, 'Mike Salomon\r\n', 'dkennedy@onee.ca\r\n', '8474837514', 'United States', 'Hello \r\n \r\nI have just took a look on your SEO for  learnquraan.us for its SEO metrics and saw that your website could use a push. \r\n \r\nWe will increase your ranks organically and safely, using only state of the art AI and whitehat methods, while providing monthly reports and outstanding support. \r\n', '2024-09-10 05:48:44');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl`
--
ALTER TABLE `tbl`
  ADD UNIQUE KEY `id` (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl`
--
ALTER TABLE `tbl`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=245;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
