<?php
   // include header //
   include_once('header.php'); // this is used for include header //
    // end of include header // ?>
<?php
   // include get code //
    include_once('get/get-code.php'); // this is used for include get code //
     // end of includeget code //
    ?> 
<?php
   // include nav //
   include_once('nav/nav.php'); // this is used for include nav //
   // end of include nav // ?>
<!-- title -->
<title>Promotion</title>
<body>
   <!-- banner start here  -->
   <section class="banner">
      <div class="bann1">
         <img class="banslides" src="images/promotionbanner.png" alt="banner1" >
         <div class="row">
            <div class="col-md-8">
               <div class="bannercontent Promotion">
                  <h1>Promotion Reward</h1>
                  <p>Pressearn platform investment starts with a three-tier development model. Three levels, it means that the agent can get three <br> levels of commission share, and can not get commission share for more than three levels. For example, if you are the user A <br>of this platform, you get the agent authority after performing the purchase task. The system will automatically form your  center<br> and promote your exclusive QR code and promotion link. B will register as a user by scanning the QR code or promotion link.<br> After completing the purchase task, A will get 16% of B's commission.At the same time, the system will automatically create a user <br>center for B to promote exclusive QR code and promotion link. C will register as a user by scanning the QR code or promotion <br>link, and after completing the purchase task, B will get 16% commission of C. A will get 8% of C; and so on, if D becomes a <br>user through C, C will get 16%, B will get 8%, and A will get 4%.
                     <br><br>Note: The commission rewards generated by all the agents' offline users are issued by the platform and will not affect the <br>commissions of all agents and offline users!
                     Agent commissions will be <br>paid at 00:30 (USA Time)
                  </p>
               </div>
            </div>
            <div class="col-md-4">
            </div>
         </div>
      </div>
      </div>
   </section>
   <!-- QR Section -->
   <section id="qr">
      <div class="container">
         <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
               <div class="box">
                  <img id='barcode' 
                     src="https://api.qrserver.com/v1/create-qr-code/?data=HelloWorld&amp;size=100x100" 
                     alt="" 
                     title="HELLO" 
                     width="120" 
                     height="120" />
                  <p>Long Press & Hold the the picture to save the Album</p>
                  <h3>Invitation code</h3>
                  <button href="" class="btn">Copy</button>
                  <br>
                  <h3>Invitation Link</h3>
                  <button href="" class="btn">Copy</a>
               </div>
            </div>
            <div class="col-md-2"></div>
         </div>
      </div>
   </section>
</body>
<?php
   // include footer //
   include_once('footer.php'); // this is used for include footer //
    // end of include footer // ?>